/**
 * Setup Site for AI
 *
 * Installs the AI Experiments plugin, enables all experiments, syncs
 * credentials, and optionally writes the ACF abilities mu-plugin for
 * sites with ACF PRO >= 6.8. Called via IPC from the UI, not exposed
 * as an MCP tool.
 */
import * as fs from 'fs';
import * as path from 'path';
import type { LocalServicesBridge, WpPlugin } from '../../local-services-bridge';
import type { RegistryStorage } from '../../../content/IndexRegistry';
import { STORAGE_KEYS } from '../../../../common/constants';
import {
  PROVIDER_TO_WP_OPTION,
  PROVIDER_PLUGIN_SLUGS,
  SUPPORTED_PROVIDERS,
  buildCredentialSyncPhp,
  CredentialEntry,
} from './credential-helpers';
import { getOllamaStatus } from '../ollama/ask-ollama';

/**
 * Path to bundled WP plugins directory.
 * Resolved from the compiled lib/ directory up to package root, then to wp-plugins/.
 * This is more robust than __dirname traversal which breaks if directory structure changes.
 */
const WP_PLUGINS_ROOT = path.resolve(__dirname, '..', '..', '..', '..', 'wp-plugins');

/**
 * Validates that a plugin directory path is safe and within the expected location.
 * Prevents path traversal attacks where a malicious wp-config.php could define
 * WP_PLUGIN_DIR to point outside the site directory.
 *
 * @throws Error if path is invalid or outside site boundaries
 */
function validatePluginPath(pluginDir: string, siteWebRoot: string): void {
  // Resolve to absolute paths to handle any '..' or symlinks
  const absolutePluginDir = path.resolve(pluginDir);
  const absoluteSiteRoot = path.resolve(siteWebRoot);

  // Security check 1: Must be inside site directory
  if (!absolutePluginDir.startsWith(absoluteSiteRoot)) {
    throw new Error(
      `Security: Plugin directory is outside site root. ` +
      `Expected inside "${absoluteSiteRoot}", got "${absolutePluginDir}"`
    );
  }

  // Security check 2: Must end with wp-content/plugins (no traversal)
  const expectedSuffix = path.join('wp-content', 'plugins');
  if (!absolutePluginDir.endsWith(expectedSuffix)) {
    throw new Error(
      `Security: Invalid plugin directory structure. ` +
      `Expected path ending with "wp-content/plugins", got "${absolutePluginDir}"`
    );
  }

  // Security check 3: No path traversal sequences in resolved path
  if (absolutePluginDir.includes('..')) {
    throw new Error(`Security: Path traversal detected in plugin directory: ${absolutePluginDir}`);
  }
}

export interface SetupAIResult {
  success: boolean;
  aiPlugin: 'installed' | 'activated' | 'already_active' | 'failed';
  providerPlugins: 'installed' | 'already_active' | 'skipped' | 'failed';
  ollamaProvider: 'installed' | 'activated' | 'already_active' | 'skipped' | 'failed';
  aiFeatures: 'enabled' | 'already_enabled' | 'skipped' | 'failed';
  credentials: 'synced' | 'skipped' | 'failed';
  acfAbilities: 'enabled' | 'already_enabled' | 'skipped' | 'failed';
  message: string;
}

interface Logger {
  info(...args: unknown[]): void;
  error(...args: unknown[]): void;
}

const ACF_MU_PLUGIN_FILENAME = 'enable-acf-abilities.php';

/**
 * PHP content for the ACF abilities mu-plugin.
 * Opts ACF PRO into the WordPress Abilities API.
 */
const ACF_MU_PLUGIN_CONTENT = `<?php
/**
 * Plugin Name: Enable ACF Abilities
 * Description: Opts ACF PRO into the WordPress Abilities API for AI tooling.
 * Version: 1.0.0
 * Auto-generated by Nexus AI.
 */
add_filter('acf/abilities/enabled', '__return_true');
`;

/**
 * All known AI Experiment IDs in WordPress 7.0.
 */
const AI_EXPERIMENT_IDS = [
  'abilities-explorer',
  'excerpt-generation',
  'alt-text-generation',
  'image-generation',
  'summarization',
  'title-generation',
];

function findPlugin(plugins: WpPlugin[], slug: string): WpPlugin | undefined {
  return plugins.find((p) => p.name === slug);
}

/**
 * Returns the absolute path to the site's wp-content/plugins directory.
 */
async function getSitePluginsDir(
  siteId: string,
  localServices: LocalServicesBridge,
): Promise<string | null> {
  try {
    const result = await localServices.wpCliRun(siteId, ['eval', "echo WP_PLUGIN_DIR;"]);
    if (result.success && result.stdout?.trim()) {
      return result.stdout.trim();
    }
  } catch {
    // Fall through
  }
  return null;
}

function meetsMinVersion(version: string, minMajor: number, minMinor: number): boolean {
  const parts = version.split('.');
  const major = parseInt(parts[0], 10);
  const minor = parseInt(parts[1] ?? '0', 10);
  if (isNaN(major)) return false;
  return major > minMajor || (major === minMajor && minor >= minMinor);
}

/**
 * Returns true if the version string is WordPress 7.0 or later.
 * Provider plugins require WP 7.0+ core's php-ai-client infrastructure.
 */
function isWp7OrLater(version: string): boolean {
  const match = version.match(/^(\d+)/);
  if (!match) return false;
  return parseInt(match[1], 10) >= 7;
}

export interface SetupAIOptions {
  /** Install the Ollama provider plugin if Ollama is running. Defaults to false. */
  enableOllama?: boolean;
}

export async function setupSiteForAI(
  siteId: string,
  localServices: LocalServicesBridge,
  registryStorage: RegistryStorage,
  logger: Logger,
  options: SetupAIOptions = {},
): Promise<SetupAIResult> {
  const tag = '[NexusAI:setup-ai]';

  // Step 1: Get current plugin list
  let plugins: WpPlugin[];
  try {
    plugins = await localServices.getPlugins(siteId);
  } catch (err) {
    const msg = `Failed to list plugins: ${err instanceof Error ? err.message : String(err)}`;
    logger.error(`${tag} ${msg}`);
    return {
      success: false,
      aiPlugin: 'failed',
      providerPlugins: 'failed',
      ollamaProvider: 'failed',
      aiFeatures: 'failed',
      credentials: 'failed',
      acfAbilities: 'failed',
      message: msg,
    };
  }

  // Step 2: Handle AI Experiments plugin ("ai")
  let aiPlugin: SetupAIResult['aiPlugin'] = 'failed';
  const existingAi = findPlugin(plugins, 'ai');

  try {
    if (!existingAi) {
      // Not installed — install and activate
      logger.info(`${tag} Installing AI Experiments plugin on site ${siteId}`);
      const result = await localServices.wpCliRun(siteId, ['plugin', 'install', 'ai', '--activate']);
      if (!result.success) {
        throw new Error(result.stdout ?? 'Unknown error');
      }
      aiPlugin = 'installed';
    } else if (existingAi.status !== 'active') {
      // Installed but inactive — activate
      logger.info(`${tag} Activating AI Experiments plugin on site ${siteId}`);
      const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai']);
      if (!result.success) {
        throw new Error(result.stdout ?? 'Unknown error');
      }
      aiPlugin = 'activated';
    } else {
      // Already active
      aiPlugin = 'already_active';
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(`${tag} AI plugin step failed: ${msg}`);
    aiPlugin = 'failed';
  }

  const storedKeys = (registryStorage.get(STORAGE_KEYS.API_KEYS) ?? {}) as Record<string, string>;
  const configuredProviders = SUPPORTED_PROVIDERS.filter((p) => storedKeys[p]);

  // Step 2b: Install AI provider plugins for configured providers
  // Each provider needs its own plugin (e.g. ai-provider-for-anthropic) to register
  // with the ProviderRegistry. Without it, the Connector Screen can't validate keys.
  //
  // Provider plugins require WP 7.0+ core — they depend on wp-includes/php-ai-client/
  // which ships the PSR-18 HTTP adapter. On older WP versions (or with the standalone
  // "ai" plugin), the provider plugin crashes with DiscoveryFailedException.
  let providerPlugins: SetupAIResult['providerPlugins'] = 'skipped';

  if (configuredProviders.length > 0 && aiPlugin !== 'failed') {
    // Check WP version — provider plugins only work on WP 7.0+
    let wpVersion: string | null = null;
    try {
      wpVersion = await localServices.getWpVersion(siteId);
    } catch {
      // Can't determine version — skip provider plugins to be safe
    }

    if (!wpVersion || !isWp7OrLater(wpVersion)) {
      logger.info(`${tag} Skipping provider plugins — WP ${wpVersion ?? 'unknown'} (requires 7.0+)`);
    } else {
      try {
        // Refresh plugin list after AI plugin install
        const currentPlugins = await localServices.getPlugins(siteId);
        let installed = 0;
        let alreadyActive = 0;

        for (const provider of configuredProviders) {
          const slug = PROVIDER_PLUGIN_SLUGS[provider];
          if (!slug) continue;

          const existing = findPlugin(currentPlugins, slug);
          if (existing && existing.status === 'active') {
            alreadyActive++;
            continue;
          }

          logger.info(`${tag} Installing provider plugin "${slug}" on site ${siteId}`);
          const result = await localServices.wpCliRun(
            siteId,
            ['plugin', 'install', slug, '--activate'],
          );

          if (!result.success) {
            logger.error(`${tag} Failed to install provider plugin "${slug}": ${result.stdout}`);
            continue;
          }

          // Health check: verify the activated plugin doesn't crash WordPress.
          // Run with skipPlugins: false so all active plugins (including the new one) are loaded.
          const healthCheck = await localServices.wpCliRun(
            siteId,
            ['eval', "echo 'healthy';"],
            { skipPlugins: false },
          );

          if (!healthCheck.success || healthCheck.stdout?.trim() !== 'healthy') {
            // Plugin crashed WordPress — deactivate it immediately (skipPlugins: true bypasses the crash)
            logger.error(`${tag} Provider plugin "${slug}" crashes WordPress — deactivating`);
            await localServices.wpCliRun(siteId, ['plugin', 'deactivate', slug]);
            continue;
          }

          installed++;
        }

        if (installed > 0) {
          providerPlugins = 'installed';
          logger.info(`${tag} Installed ${installed} provider plugin(s) on site ${siteId}`);
        } else if (alreadyActive === configuredProviders.length) {
          providerPlugins = 'already_active';
        } else {
          providerPlugins = 'failed';
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        logger.error(`${tag} Provider plugin step failed: ${msg}`);
        providerPlugins = 'failed';
      }
    }
  }

  // Step 2c: Install Ollama provider plugin (only when explicitly requested)
  let ollamaProvider: SetupAIResult['ollamaProvider'] = 'skipped';

  if (options.enableOllama && aiPlugin !== 'failed') {
    const ollamaStatus = getOllamaStatus();

    if (!ollamaStatus.available) {
      logger.info(`${tag} Skipping Ollama provider — Ollama not running`);
    } else {
      try {
        // Refresh plugin list
        const currentPlugins = await localServices.getPlugins(siteId);
        const existingOllama = findPlugin(currentPlugins, 'ai-provider-for-ollama');

        if (existingOllama && existingOllama.status === 'active') {
          ollamaProvider = 'already_active';
        } else if (existingOllama) {
          // Installed but inactive — activate
          const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai-provider-for-ollama']);
          if (result.success) {
            ollamaProvider = 'activated';
          } else {
            throw new Error(result.stdout ?? 'Failed to activate');
          }
        } else {
          // Not installed — copy from bundled source and activate
          const sitePluginsDir = await getSitePluginsDir(siteId, localServices);
          if (!sitePluginsDir) {
            logger.error(`${tag} Could not determine site plugins directory`);
            ollamaProvider = 'failed';
          } else {
            // Security: Validate plugin path before file operations
            let pathValid = false;
            try {
              const site = localServices.resolveSiteObject(siteId) as any;
              validatePluginPath(sitePluginsDir, site.paths.webRoot);
              pathValid = true;
            } catch (validationErr) {
              const msg = validationErr instanceof Error ? validationErr.message : String(validationErr);
              logger.error(`${tag} ${msg}`);
              ollamaProvider = 'failed';
            }

            if (pathValid) {
              const pluginDest = path.join(sitePluginsDir, 'ai-provider-for-ollama');
              const pluginSource = path.join(WP_PLUGINS_ROOT, 'ai-provider-for-ollama');

              if (!fs.existsSync(pluginSource)) {
                logger.error(`${tag} Ollama provider plugin source not found at ${pluginSource}`);
                ollamaProvider = 'failed';
              } else {
                try {
                  fs.cpSync(pluginSource, pluginDest, { recursive: true });
                } catch (copyErr) {
                  const msg = copyErr instanceof Error ? copyErr.message : String(copyErr);
                  logger.error(`${tag} Failed to copy Ollama provider plugin: ${msg}`);
                  ollamaProvider = 'failed';
                  throw copyErr;
                }

                const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai-provider-for-ollama']);
                if (!result.success) {
                  throw new Error(result.stdout ?? 'Failed to activate');
                }

                // Health check: verify the plugin doesn't crash WordPress
                const healthCheck = await localServices.wpCliRun(
                  siteId,
                  ['eval', "echo 'healthy';"],
                  { skipPlugins: false },
                );

                if (!healthCheck.success || healthCheck.stdout?.trim() !== 'healthy') {
                  logger.error(`${tag} Ollama provider plugin crashes WordPress — deactivating`);
                  await localServices.wpCliRun(siteId, ['plugin', 'deactivate', 'ai-provider-for-ollama']);
                  ollamaProvider = 'failed';
                } else {
                  ollamaProvider = 'installed';
                }
              }
            }
          }
        }

        if (ollamaProvider === 'installed' || ollamaProvider === 'activated') {
          logger.info(`${tag} Ollama provider plugin ${ollamaProvider} on site ${siteId}`);
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        logger.error(`${tag} Ollama provider step failed: ${msg}`);
        ollamaProvider = 'failed';
      }
    }
  }

  // Step 3: Enable all AI experiments
  let aiFeatures: SetupAIResult['aiFeatures'] = 'skipped';

  if (aiPlugin !== 'failed') {
    try {
      const phpLines: string[] = [];
      // Set the global toggle
      phpLines.push("update_option('ai_experiments_enabled', '1');");
      // Set each experiment toggle
      for (const id of AI_EXPERIMENT_IDS) {
        phpLines.push(`update_option('ai_experiment_${id}_enabled', '1');`);
      }
      phpLines.push(`echo json_encode(['enabled' => ${AI_EXPERIMENT_IDS.length + 1}]);`);

      const phpCode = phpLines.join(' ');
      // skipPlugins defaults to true — safe because we're writing simple option values
      const result = await localServices.wpCliRun(
        siteId,
        ['eval', phpCode],
      );

      if (result.success) {
        try {
          const parsed = JSON.parse((result.stdout ?? '').trim());
          aiFeatures = parsed.enabled > 0 ? 'enabled' : 'failed';
        } catch {
          // Got stdout but couldn't parse — assume success if command succeeded
          aiFeatures = 'enabled';
        }
      } else {
        throw new Error(result.stdout ?? 'Unknown error');
      }

      logger.info(`${tag} Enabled AI experiments on site ${siteId}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`${tag} AI features step failed: ${msg}`);
      aiFeatures = 'failed';
    }
  }

  // Step 4: Sync credentials
  let credentials: SetupAIResult['credentials'] = 'skipped';

  if (configuredProviders.length > 0 && aiPlugin !== 'failed') {
    try {
      const entries: CredentialEntry[] = configuredProviders.map((provider) => ({
        provider,
        key: storedKeys[provider],
        optionName: PROVIDER_TO_WP_OPTION[provider],
      }));

      const phpCode = buildCredentialSyncPhp(entries);
      // skipPlugins defaults to true — safe because we remove all filters and verify via $wpdb
      const result = await localServices.wpCliRun(
        siteId,
        ['eval', phpCode],
      );

      if (result.success) {
        credentials = 'synced';
        logger.info(`${tag} Synced ${configuredProviders.length} credential(s) to site ${siteId}`);
      } else {
        throw new Error(result.stdout ?? 'Unknown error');
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`${tag} Credential sync step failed: ${msg}`);
      credentials = 'failed';
    }
  }

  // Step 5: Handle ACF abilities mu-plugin
  let acfAbilities: SetupAIResult['acfAbilities'] = 'skipped';
  const acfPlugin = findPlugin(plugins, 'advanced-custom-fields-pro');

  if (acfPlugin && acfPlugin.status === 'active' && meetsMinVersion(acfPlugin.version, 6, 8)) {
    try {
      // Check if mu-plugin already exists
      const checkPhp = `echo file_exists(WPMU_PLUGIN_DIR . '/${ACF_MU_PLUGIN_FILENAME}') ? 'exists' : 'missing';`;
      const checkResult = await localServices.wpCliRun(siteId, ['eval', checkPhp]);

      if (checkResult.success && checkResult.stdout?.trim() === 'exists') {
        acfAbilities = 'already_enabled';
      } else {
        // Write the mu-plugin
        logger.info(`${tag} Writing ACF abilities mu-plugin on site ${siteId}`);
        const phpContent = ACF_MU_PLUGIN_CONTENT.replace(/'/g, "\\'");
        const writePhp = [
          `$dir = WPMU_PLUGIN_DIR;`,
          `if (!is_dir($dir)) { wp_mkdir_p($dir); }`,
          `$file = $dir . '/${ACF_MU_PLUGIN_FILENAME}';`,
          `$content = '${phpContent}';`,
          `$written = file_put_contents($file, $content);`,
          `echo $written !== false ? 'ok' : 'fail';`,
        ].join(' ');

        const writeResult = await localServices.wpCliRun(siteId, ['eval', writePhp]);
        if (writeResult.success && writeResult.stdout?.trim() === 'ok') {
          acfAbilities = 'enabled';
        } else {
          throw new Error(writeResult.stdout ?? 'Failed to write mu-plugin');
        }
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`${tag} ACF abilities step failed: ${msg}`);
      acfAbilities = 'failed';
    }
  }

  // Build result
  const success = aiPlugin !== 'failed';
  const parts: string[] = [];

  switch (aiPlugin) {
    case 'installed': parts.push('AI Experiments plugin installed and activated'); break;
    case 'activated': parts.push('AI Experiments plugin activated'); break;
    case 'already_active': parts.push('AI Experiments plugin already active'); break;
    case 'failed': parts.push('AI Experiments plugin setup failed'); break;
  }

  switch (providerPlugins) {
    case 'installed': parts.push('AI provider plugin(s) installed'); break;
    case 'already_active': parts.push('AI provider plugin(s) already active'); break;
    case 'skipped': break;
    case 'failed': parts.push('AI provider plugin installation failed'); break;
  }

  switch (ollamaProvider) {
    case 'installed': parts.push('Ollama provider plugin installed'); break;
    case 'activated': parts.push('Ollama provider plugin activated'); break;
    case 'already_active': parts.push('Ollama provider plugin already active'); break;
    case 'skipped': break;
    case 'failed': parts.push('Ollama provider plugin failed'); break;
  }

  switch (aiFeatures) {
    case 'enabled': parts.push('All AI experiments enabled'); break;
    case 'skipped': break; // Don't clutter message if skipped due to plugin failure
    case 'failed': parts.push('AI experiment enablement failed'); break;
  }

  switch (credentials) {
    case 'synced': parts.push(`${configuredProviders.length} API key(s) synced`); break;
    case 'skipped': parts.push('No API keys configured to sync'); break;
    case 'failed': parts.push('Credential sync failed'); break;
  }

  switch (acfAbilities) {
    case 'enabled': parts.push('ACF abilities mu-plugin created'); break;
    case 'already_enabled': parts.push('ACF abilities mu-plugin already present'); break;
    case 'skipped': parts.push('ACF abilities skipped (ACF PRO >= 6.8 not found)'); break;
    case 'failed': parts.push('ACF abilities mu-plugin failed'); break;
  }

  const message = parts.join('. ') + '.';
  logger.info(`${tag} Result for site ${siteId}: ${message}`);

  return {
    success,
    aiPlugin,
    providerPlugins,
    ollamaProvider,
    aiFeatures,
    credentials,
    acfAbilities,
    message,
  };
}
