/**
 * Setup Site for AI
 *
 * Installs the AI Experiments plugin, enables all experiments, syncs
 * credentials, and optionally writes the ACF abilities mu-plugin for
 * sites with ACF PRO >= 6.8. Called via IPC from the UI, not exposed
 * as an MCP tool.
 */
import * as fs from 'fs';
import * as path from 'path';
import type { LocalServicesBridge, WpPlugin } from '../../local-services-bridge';
import type { RegistryStorage } from '../../../content/IndexRegistry';
import { STORAGE_KEYS } from '../../../../common/constants';
import {
  PROVIDER_TO_WP_OPTION,
  PROVIDER_PLUGIN_SLUGS,
  SUPPORTED_PROVIDERS,
  buildCredentialSyncPhp,
  CredentialEntry,
} from './credential-helpers';
import { getOllamaStatus } from '../ollama/ask-ollama';
import { redactCredentials } from '../../security/credential-redaction';
import { generateMuPluginContent } from '../../../ai-gateway/mu-plugin-template';

/**
 * Path to bundled WP plugins directory.
 * Resolved from the compiled lib/ directory up to package root, then to wp-plugins/.
 * This is more robust than __dirname traversal which breaks if directory structure changes.
 */
const WP_PLUGINS_ROOT = path.resolve(__dirname, '..', '..', '..', '..', 'wp-plugins');

/**
 * Validates that a plugin directory path is safe and within the expected location.
 * Prevents path traversal attacks where a malicious wp-config.php could define
 * WP_PLUGIN_DIR to point outside the site directory.
 *
 * @throws Error if path is invalid or outside site boundaries
 */
function validatePluginPath(pluginDir: string, siteWebRoot: string): void {
  // Resolve to absolute paths to handle any '..' or symlinks
  const absolutePluginDir = path.resolve(pluginDir);
  const absoluteSiteRoot = path.resolve(siteWebRoot);

  // Security check 1: Must be inside site directory
  if (!absolutePluginDir.startsWith(absoluteSiteRoot)) {
    throw new Error(
      `Security: Plugin directory is outside site root. ` +
      `Expected inside "${absoluteSiteRoot}", got "${absolutePluginDir}"`
    );
  }

  // Security check 2: Must end with wp-content/plugins (no traversal)
  const expectedSuffix = path.join('wp-content', 'plugins');
  if (!absolutePluginDir.endsWith(expectedSuffix)) {
    throw new Error(
      `Security: Invalid plugin directory structure. ` +
      `Expected path ending with "wp-content/plugins", got "${absolutePluginDir}"`
    );
  }

  // Security check 3: No path traversal sequences in resolved path
  if (absolutePluginDir.includes('..')) {
    throw new Error(`Security: Path traversal detected in plugin directory: ${absolutePluginDir}`);
  }
}

export interface SetupAIResult {
  success: boolean;
  aiPlugin: 'installed' | 'activated' | 'already_active' | 'failed';
  connectorPlugin: 'installed' | 'already_active' | 'skipped' | 'failed';
  providerPlugins: 'installed' | 'already_active' | 'skipped' | 'failed';
  gatewayProvider: 'installed' | 'activated' | 'already_active' | 'skipped' | 'failed';
  ollamaProvider: 'installed' | 'activated' | 'already_active' | 'skipped' | 'failed';
  aiFeatures: 'enabled' | 'already_enabled' | 'skipped' | 'failed';
  credentials: 'synced' | 'skipped' | 'failed';
  acfAbilities: 'enabled' | 'already_enabled' | 'skipped' | 'failed';
  message: string;
}

interface Logger {
  info(...args: unknown[]): void;
  error(...args: unknown[]): void;
}

const ACF_MU_PLUGIN_FILENAME = 'enable-acf-abilities.php';

/**
 * PHP content for the ACF abilities mu-plugin.
 * Opts ACF PRO into the WordPress Abilities API.
 */
const ACF_MU_PLUGIN_CONTENT = `<?php
/**
 * Plugin Name: Enable ACF Abilities
 * Description: Opts ACF PRO into the WordPress Abilities API for AI tooling.
 * Version: 1.0.0
 * Auto-generated by Nexus AI.
 */
add_filter('acf/abilities/enabled', '__return_true');
`;

/**
 * All known AI Experiment IDs in WordPress 7.0.
 */
const AI_EXPERIMENT_IDS = [
  'abilities-explorer',
  'excerpt-generation',
  'alt-text-generation',
  'image-generation',
  'summarization',
  'title-generation',
];

function findPlugin(plugins: WpPlugin[], slug: string): WpPlugin | undefined {
  return plugins.find((p) => p.name === slug);
}

/**
 * Returns the absolute path to the site's wp-content/plugins directory.
 * Uses direct path access (doesn't require site to be running).
 */
function getSitePluginsDir(
  siteId: string,
  localServices: LocalServicesBridge,
): string | null {
  try {
    const site = localServices.resolveSiteObject(siteId) as any;
    if (site?.paths?.webRoot) {
      return path.join(site.paths.webRoot, 'wp-content', 'plugins');
    }
  } catch {
    // Fall through
  }
  return null;
}

function meetsMinVersion(version: string, minMajor: number, minMinor: number): boolean {
  const parts = version.split('.');
  const major = parseInt(parts[0], 10);
  const minor = parseInt(parts[1] ?? '0', 10);
  if (isNaN(major)) return false;
  return major > minMajor || (major === minMajor && minor >= minMinor);
}

/**
 * Returns true if the version string is WordPress 7.0 or later.
 * Provider plugins require WP 7.0+ core's php-ai-client infrastructure.
 */
function isWp7OrLater(version: string): boolean {
  const match = version.match(/^(\d+)/);
  if (!match) return false;
  return parseInt(match[1], 10) >= 7;
}

export interface SetupAIOptions {
  /** Install the Ollama provider plugin if Ollama is running. Defaults to false. */
  enableOllama?: boolean;
}

export async function setupSiteForAI(
  siteId: string,
  localServices: LocalServicesBridge,
  registryStorage: RegistryStorage,
  logger: Logger,
  options: SetupAIOptions = {},
): Promise<SetupAIResult> {
  const tag = '[NexusAI:setup-ai]';

  // Step 0: Check WordPress version (AI plugin requires WP 7.0+)
  let wpVersion: string | null;
  try {
    wpVersion = await localServices.getWpVersion(siteId);
  } catch (err) {
    const msg = `Failed to get WordPress version: ${err instanceof Error ? err.message : String(err)}`;
    logger.error(`${tag} ${msg}`);
    return {
      success: false,
      aiPlugin: 'failed',
      connectorPlugin: 'failed',
      providerPlugins: 'failed',
      gatewayProvider: 'failed',
      ollamaProvider: 'failed',
      aiFeatures: 'failed',
      credentials: 'failed',
      acfAbilities: 'failed',
      message: msg,
    };
  }

  if (!isWp7OrLater(wpVersion || '')) {
    const msg = `WordPress ${wpVersion || 'unknown'} is not supported. AI Experiments plugin requires WordPress 7.0 or later. Please upgrade WordPress first.`;
    logger.error(`${tag} ${msg}`);
    return {
      success: false,
      aiPlugin: 'failed',
      connectorPlugin: 'skipped',
      providerPlugins: 'skipped',
      gatewayProvider: 'skipped',
      ollamaProvider: 'skipped',
      aiFeatures: 'skipped',
      credentials: 'skipped',
      acfAbilities: 'skipped',
      message: msg,
    };
  }

  // Step 1: Get current plugin list
  let plugins: WpPlugin[];
  try {
    plugins = await localServices.getPlugins(siteId);
  } catch (err) {
    const msg = `Failed to list plugins: ${err instanceof Error ? err.message : String(err)}`;
    logger.error(`${tag} ${msg}`);
    return {
      success: false,
      aiPlugin: 'failed',
      connectorPlugin: 'failed',
      providerPlugins: 'failed',
      gatewayProvider: 'failed',
      ollamaProvider: 'failed',
      aiFeatures: 'failed',
      credentials: 'failed',
      acfAbilities: 'failed',
      message: msg,
    };
  }

  // Step 2: Handle AI Experiments plugin ("ai")
  let aiPlugin: SetupAIResult['aiPlugin'] = 'failed';
  const existingAi = findPlugin(plugins, 'ai');

  try {
    if (!existingAi) {
      // Not installed — copy from bundled source and activate
      const sitePluginsDir = getSitePluginsDir(siteId, localServices);
      if (!sitePluginsDir) {
        throw new Error('Could not determine site plugins directory');
      }

      // Security: Validate plugin path before file operations
      const site = localServices.resolveSiteObject(siteId) as any;
      validatePluginPath(sitePluginsDir, site.paths.webRoot);

      const pluginDest = path.join(sitePluginsDir, 'ai');
      const pluginSource = path.join(WP_PLUGINS_ROOT, 'ai');

      if (!fs.existsSync(pluginSource)) {
        throw new Error(`AI Experiments plugin source not found at ${pluginSource}`);
      }

      logger.info(`${tag} Copying AI Experiments plugin to site ${siteId}`);
      fs.cpSync(pluginSource, pluginDest, { recursive: true });

      logger.info(`${tag} Activating AI Experiments plugin on site ${siteId}`);
      const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai']);
      if (!result.success) {
        throw new Error(result.stdout ?? 'Failed to activate');
      }

      // Health check: verify the plugin doesn't crash WordPress
      const healthCheck = await localServices.wpCliRun(
        siteId,
        ['eval', "echo 'healthy';"],
        { skipPlugins: false },
      );

      if (!healthCheck.success || healthCheck.stdout?.trim() !== 'healthy') {
        logger.error(`${tag} AI plugin crashes WordPress — deactivating`);
        await localServices.wpCliRun(siteId, ['plugin', 'deactivate', 'ai']);
        throw new Error('AI plugin failed health check');
      }

      aiPlugin = 'installed';
    } else if (existingAi.status !== 'active') {
      // Installed but inactive — activate
      logger.info(`${tag} Activating AI Experiments plugin on site ${siteId}`);
      const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai']);
      if (!result.success) {
        throw new Error(result.stdout ?? 'Unknown error');
      }
      aiPlugin = 'activated';
    } else {
      // Already active
      aiPlugin = 'already_active';
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(`${tag} AI plugin step failed: ${msg}`);
    aiPlugin = 'failed';
  }

  // Step 1b: Install Nexus AI Connector plugin (event webhooks)
  let connectorPlugin: 'installed' | 'already_active' | 'skipped' | 'failed' = 'skipped';

  if (aiPlugin !== 'failed') {
    // Refresh plugin list
    try {
      plugins = await localServices.getPlugins(siteId);
    } catch {
      // Continue with stale list
    }

    const existingConnector = findPlugin(plugins, 'nexus-ai-connector');

    if (!existingConnector) {
      try {
        const sitePluginsDir = getSitePluginsDir(siteId, localServices);
        if (sitePluginsDir) {
          // Security: Validate plugin path
          const site = localServices.resolveSiteObject(siteId) as any;
          validatePluginPath(sitePluginsDir, site.paths.webRoot);

          const pluginDest = path.join(sitePluginsDir, 'nexus-ai-connector');
          const pluginSource = path.join(WP_PLUGINS_ROOT, 'nexus-ai-connector');

          if (fs.existsSync(pluginSource)) {
            logger.info(`${tag} Installing Nexus AI Connector plugin on site ${siteId}`);
            fs.cpSync(pluginSource, pluginDest, { recursive: true });

            const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'nexus-ai-connector']);
            if (!result.success) {
              throw new Error(result.stdout ?? 'Failed to activate');
            }

            // Health check
            const healthCheck = await localServices.wpCliRun(
              siteId,
              ['eval', "echo 'healthy';"],
              { skipPlugins: false },
            );

            if (!healthCheck.success || healthCheck.stdout?.trim() !== 'healthy') {
              logger.error(`${tag} Nexus AI Connector crashes WordPress — deactivating`);
              await localServices.wpCliRun(siteId, ['plugin', 'deactivate', 'nexus-ai-connector']);
              throw new Error('Nexus AI Connector failed health check');
            }

            connectorPlugin = 'installed';
            logger.info(`${tag} Nexus AI Connector installed on site ${siteId}`);

            // Configure connector plugin via MU plugin (defines webhook constants)
            try {
              const webhookInfo = registryStorage.get('http_webhook_info') as any;
              if (webhookInfo && webhookInfo.url && webhookInfo.authToken) {
                logger.info(`${tag} Configuring Nexus AI Connector via MU plugin`);

                const site = localServices.resolveSiteObject(siteId) as any;
                const muPluginsDir = path.join(site.paths.webRoot, 'wp-content', 'mu-plugins');

                // Create mu-plugins directory if needed
                if (!fs.existsSync(muPluginsDir)) {
                  fs.mkdirSync(muPluginsDir, { recursive: true });
                }

                // Get AI Gateway info if available
                const aiProxyInfo = registryStorage.get('ai_proxy_info') as any;

                // Generate MU plugin content with caller detection
                const muPluginContent = generateMuPluginContent({
                  webhookUrl: webhookInfo.url,
                  webhookAuthToken: webhookInfo.authToken,
                  siteId,
                  aiGatewayUrl: aiProxyInfo?.url,
                  aiGatewayToken: aiProxyInfo?.authToken,
                });

                // Clean up old MU plugin file if it exists (pre-unified template)
                const oldMuPluginPath = path.join(muPluginsDir, 'nexus-ai-gateway-config.php');
                if (fs.existsSync(oldMuPluginPath)) {
                  fs.unlinkSync(oldMuPluginPath);
                  logger.info(`${tag} Removed obsolete nexus-ai-gateway-config.php MU plugin`);
                }

                const muPluginPath = path.join(muPluginsDir, 'nexus-ai-connector-config.php');
                fs.writeFileSync(muPluginPath, muPluginContent);

                logger.info(`${tag} Nexus AI Connector configured with webhook ${webhookInfo.url}/wp-events`);
                if (aiProxyInfo?.url) {
                  logger.info(`${tag} AI Gateway caller detection enabled`);
                }
              } else {
                logger.info(`${tag} HTTP webhook info not available, connector will need manual configuration`);
              }
            } catch (err) {
              logger.error(`${tag} Connector configuration failed: ${err}`);
              // Non-fatal - plugin is installed and can be configured manually
            }

            // Refresh plugins for next steps
            try {
              plugins = await localServices.getPlugins(siteId);
            } catch {
              // Continue
            }
          } else {
            logger.info(`${tag} Nexus AI Connector not bundled at ${pluginSource}, skipping`);
          }
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        logger.error(`${tag} Nexus AI Connector installation failed: ${redactCredentials(msg)}`);
        connectorPlugin = 'failed';
      }
    } else if (existingConnector.status === 'active') {
      connectorPlugin = 'already_active';

      // Make sure connector is configured even if already active
      try {
        const webhookInfo = registryStorage.get('http_webhook_info') as any;
        if (webhookInfo && webhookInfo.url && webhookInfo.authToken) {
          const site = localServices.resolveSiteObject(siteId) as any;
          const muPluginPath = path.join(site.paths.webRoot, 'wp-content', 'mu-plugins', 'nexus-ai-connector-config.php');

          // Only write if it doesn't exist or is outdated
          if (!fs.existsSync(muPluginPath)) {
            logger.info(`${tag} Configuring existing Nexus AI Connector via MU plugin`);

            const muPluginsDir = path.join(site.paths.webRoot, 'wp-content', 'mu-plugins');
            if (!fs.existsSync(muPluginsDir)) {
              fs.mkdirSync(muPluginsDir, { recursive: true });
            }

            // Get AI Gateway info if available
            const aiProxyInfo = registryStorage.get('ai_proxy_info') as any;

            // Generate MU plugin content with caller detection
            const muPluginContent = generateMuPluginContent({
              webhookUrl: webhookInfo.url,
              webhookAuthToken: webhookInfo.authToken,
              siteId,
              aiGatewayUrl: aiProxyInfo?.url,
              aiGatewayToken: aiProxyInfo?.authToken,
            });

            fs.writeFileSync(muPluginPath, muPluginContent);
            logger.info(`${tag} Nexus AI Connector configured`);
            if (aiProxyInfo?.url) {
              logger.info(`${tag} AI Gateway caller detection enabled`);
            }
          }
        }
      } catch (err) {
        logger.error(`${tag} Connector configuration failed: ${err}`);
      }
    } else {
      // Installed but not active - activate it
      try {
        logger.info(`${tag} Activating Nexus AI Connector on site ${siteId}`);
        const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'nexus-ai-connector']);
        if (result.success) {
          connectorPlugin = 'already_active';
          // Refresh plugins
          try {
            plugins = await localServices.getPlugins(siteId);
          } catch {
            // Continue
          }
        }
      } catch (err) {
        logger.error(`${tag} Failed to activate Nexus AI Connector: ${err}`);
        connectorPlugin = 'failed';
      }
    }
  }

  const storedKeys = (registryStorage.get(STORAGE_KEYS.API_KEYS) ?? {}) as Record<string, string>;
  const configuredProviders = SUPPORTED_PROVIDERS.filter((p) => storedKeys[p]);

  // Step 2b: Install AI provider plugins for configured providers
  // Each provider needs its own plugin (e.g. ai-provider-for-anthropic) to register
  // with the ProviderRegistry. Without it, the Connector Screen can't validate keys.
  //
  // Provider plugins require WP 7.0+ core — they depend on wp-includes/php-ai-client/
  // which ships the PSR-18 HTTP adapter. On older WP versions (or with the standalone
  // "ai" plugin), the provider plugin crashes with DiscoveryFailedException.
  let providerPlugins: SetupAIResult['providerPlugins'] = 'skipped';

  if (configuredProviders.length > 0 && aiPlugin !== 'failed') {
    // Check WP version — provider plugins only work on WP 7.0+
    let wpVersion: string | null = null;
    try {
      wpVersion = await localServices.getWpVersion(siteId);
    } catch {
      // Can't determine version — skip provider plugins to be safe
    }

    if (!wpVersion || !isWp7OrLater(wpVersion)) {
      logger.info(`${tag} Skipping provider plugins — WP ${wpVersion ?? 'unknown'} (requires 7.0+)`);
    } else {
      try {
        // Refresh plugin list after AI plugin install
        const currentPlugins = await localServices.getPlugins(siteId);
        let installed = 0;
        let alreadyActive = 0;

        for (const provider of configuredProviders) {
          const slug = PROVIDER_PLUGIN_SLUGS[provider];
          if (!slug) continue;

          const existing = findPlugin(currentPlugins, slug);
          if (existing && existing.status === 'active') {
            alreadyActive++;
            continue;
          }

          logger.info(`${tag} Installing provider plugin "${slug}" on site ${siteId}`);
          const result = await localServices.wpCliRun(
            siteId,
            ['plugin', 'install', slug, '--activate'],
          );

          if (!result.success) {
            logger.error(`${tag} Failed to install provider plugin "${slug}": ${redactCredentials(result.stdout ?? '')}`);
            continue;
          }

          // Health check: verify the activated plugin doesn't crash WordPress.
          // Run with skipPlugins: false so all active plugins (including the new one) are loaded.
          const healthCheck = await localServices.wpCliRun(
            siteId,
            ['eval', "echo 'healthy';"],
            { skipPlugins: false },
          );

          if (!healthCheck.success || healthCheck.stdout?.trim() !== 'healthy') {
            // Plugin crashed WordPress — deactivate it immediately (skipPlugins: true bypasses the crash)
            logger.error(`${tag} Provider plugin "${slug}" crashes WordPress — deactivating`);
            await localServices.wpCliRun(siteId, ['plugin', 'deactivate', slug]);
            continue;
          }

          installed++;
        }

        if (installed > 0) {
          providerPlugins = 'installed';
          logger.info(`${tag} Installed ${installed} provider plugin(s) on site ${siteId}`);
        } else if (alreadyActive === configuredProviders.length) {
          providerPlugins = 'already_active';
        } else {
          providerPlugins = 'failed';
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        logger.error(`${tag} Provider plugin step failed: ${redactCredentials(msg)}`);
        providerPlugins = 'failed';
      }
    }
  }

  // Step 2c: Install Local Gateway provider plugin (centralized AI routing)
  let gatewayProvider: 'installed' | 'activated' | 'already_active' | 'skipped' | 'failed' = 'skipped';

  if (aiPlugin !== 'failed') {
    try {
      // Refresh plugin list
      const currentPlugins = await localServices.getPlugins(siteId);
      const existingGateway = findPlugin(currentPlugins, 'ai-provider-for-local-gateway');

      if (existingGateway && existingGateway.status === 'active') {
        gatewayProvider = 'already_active';
      } else if (existingGateway) {
        // Installed but inactive — activate
        const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai-provider-for-local-gateway']);
        if (result.success) {
          gatewayProvider = 'activated';
        } else {
          throw new Error(result.stdout ?? 'Failed to activate');
        }
      } else {
        // Not installed — copy from bundled source and activate
        const sitePluginsDir = getSitePluginsDir(siteId, localServices);
        if (!sitePluginsDir) {
          logger.error(`${tag} Could not determine site plugins directory`);
          gatewayProvider = 'failed';
        } else {
          // Security: Validate plugin path before file operations
          const site = localServices.resolveSiteObject(siteId) as any;
          validatePluginPath(sitePluginsDir, site.paths.webRoot);

          const pluginDest = path.join(sitePluginsDir, 'ai-provider-for-local-gateway');
          const pluginSource = path.join(WP_PLUGINS_ROOT, 'ai-provider-for-local-gateway');

          if (!fs.existsSync(pluginSource)) {
            logger.info(`${tag} Local Gateway provider plugin not bundled at ${pluginSource}, skipping`);
            gatewayProvider = 'skipped';
          } else {
            try {
              fs.cpSync(pluginSource, pluginDest, { recursive: true });

              const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai-provider-for-local-gateway']);
              if (!result.success) {
                throw new Error(result.stdout ?? 'Failed to activate');
              }

              // Health check: verify the plugin doesn't crash WordPress
              const healthCheck = await localServices.wpCliRun(
                siteId,
                ['eval', "echo 'healthy';"],
                { skipPlugins: false },
              );

              if (!healthCheck.success || healthCheck.stdout?.trim() !== 'healthy') {
                logger.error(`${tag} Local Gateway provider plugin crashes WordPress — deactivating`);
                await localServices.wpCliRun(siteId, ['plugin', 'deactivate', 'ai-provider-for-local-gateway']);
                gatewayProvider = 'failed';
              } else {
                gatewayProvider = 'installed';
                logger.info(`${tag} Local Gateway provider plugin installed on site ${siteId}`);
              }
            } catch (copyErr) {
              const msg = copyErr instanceof Error ? copyErr.message : String(copyErr);
              logger.error(`${tag} Failed to install Local Gateway provider plugin: ${redactCredentials(msg)}`);
              gatewayProvider = 'failed';
            }
          }
        }
      }

      // Gateway provider configuration is handled by the unified nexus-ai-connector-config.php MU plugin
      // created earlier in this function (see lines 336-369). No separate MU plugin needed.
      if (gatewayProvider === 'installed' || gatewayProvider === 'activated' || gatewayProvider === 'already_active') {
        logger.info(`${tag} Local Gateway provider uses configuration from nexus-ai-connector-config.php MU plugin`);
      }

      if (gatewayProvider === 'installed' || gatewayProvider === 'activated') {
        logger.info(`${tag} Local Gateway provider plugin ${gatewayProvider} on site ${siteId}`);
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`${tag} Local Gateway provider step failed: ${redactCredentials(msg)}`);
      gatewayProvider = 'failed';
    }
  }

  // Step 2d: Install Ollama provider plugin (only when explicitly requested)
  let ollamaProvider: SetupAIResult['ollamaProvider'] = 'skipped';

  if (options.enableOllama && aiPlugin !== 'failed') {
    const ollamaStatus = getOllamaStatus();

    if (!ollamaStatus.available) {
      logger.info(`${tag} Skipping Ollama provider — Ollama not running`);
    } else {
      try {
        // Refresh plugin list
        const currentPlugins = await localServices.getPlugins(siteId);
        const existingOllama = findPlugin(currentPlugins, 'ai-provider-for-ollama');

        if (existingOllama && existingOllama.status === 'active') {
          ollamaProvider = 'already_active';
        } else if (existingOllama) {
          // Installed but inactive — activate
          const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai-provider-for-ollama']);
          if (result.success) {
            ollamaProvider = 'activated';
          } else {
            throw new Error(result.stdout ?? 'Failed to activate');
          }
        } else {
          // Not installed — copy from bundled source and activate
          const sitePluginsDir = getSitePluginsDir(siteId, localServices);
          if (!sitePluginsDir) {
            logger.error(`${tag} Could not determine site plugins directory`);
            ollamaProvider = 'failed';
          } else {
            // Security: Validate plugin path before file operations
            let pathValid = false;
            try {
              const site = localServices.resolveSiteObject(siteId) as any;
              validatePluginPath(sitePluginsDir, site.paths.webRoot);
              pathValid = true;
            } catch (validationErr) {
              const msg = validationErr instanceof Error ? validationErr.message : String(validationErr);
              logger.error(`${tag} ${redactCredentials(msg)}`);
              ollamaProvider = 'failed';
            }

            if (pathValid) {
              const pluginDest = path.join(sitePluginsDir, 'ai-provider-for-ollama');
              const pluginSource = path.join(WP_PLUGINS_ROOT, 'ai-provider-for-ollama');

              if (!fs.existsSync(pluginSource)) {
                logger.error(`${tag} Ollama provider plugin source not found at ${pluginSource}`);
                ollamaProvider = 'failed';
              } else {
                try {
                  fs.cpSync(pluginSource, pluginDest, { recursive: true });
                } catch (copyErr) {
                  const msg = copyErr instanceof Error ? copyErr.message : String(copyErr);
                  logger.error(`${tag} Failed to copy Ollama provider plugin: ${redactCredentials(msg)}`);
                  ollamaProvider = 'failed';
                  throw copyErr;
                }

                const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai-provider-for-ollama']);
                if (!result.success) {
                  throw new Error(result.stdout ?? 'Failed to activate');
                }

                // Health check: verify the plugin doesn't crash WordPress
                const healthCheck = await localServices.wpCliRun(
                  siteId,
                  ['eval', "echo 'healthy';"],
                  { skipPlugins: false },
                );

                if (!healthCheck.success || healthCheck.stdout?.trim() !== 'healthy') {
                  logger.error(`${tag} Ollama provider plugin crashes WordPress — deactivating`);
                  await localServices.wpCliRun(siteId, ['plugin', 'deactivate', 'ai-provider-for-ollama']);
                  ollamaProvider = 'failed';
                } else {
                  ollamaProvider = 'installed';
                }
              }
            }
          }
        }

        if (ollamaProvider === 'installed' || ollamaProvider === 'activated') {
          logger.info(`${tag} Ollama provider plugin ${ollamaProvider} on site ${siteId}`);
        }
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        logger.error(`${tag} Ollama provider step failed: ${redactCredentials(msg)}`);
        ollamaProvider = 'failed';
      }
    }
  }

  // Step 3: Enable all AI features
  let aiFeatures: SetupAIResult['aiFeatures'] = 'skipped';

  if (aiPlugin !== 'failed') {
    try {
      const phpLines: string[] = [];
      // Set the main AI features toggle (Settings → AI → Enable AI Features checkbox)
      // This is the global master switch that enables/disables all AI features
      phpLines.push("update_option('wpai_features_enabled', '1');");

      // Set each individual feature toggle to enabled
      // These correspond to the individual checkboxes in the AI settings page
      for (const id of AI_EXPERIMENT_IDS) {
        phpLines.push(`update_option('wpai_feature_${id}_enabled', '1');`);
      }

      // Verify the options were actually written by reading them back
      phpLines.push("$verified = array();");
      phpLines.push("$verified['global'] = get_option('wpai_features_enabled') === '1';");
      for (const id of AI_EXPERIMENT_IDS) {
        phpLines.push(`$verified['${id}'] = get_option('wpai_feature_${id}_enabled') === '1';`);
      }
      phpLines.push("echo json_encode($verified);");

      const phpCode = phpLines.join(' ');
      // skipPlugins defaults to true — safe because we're writing simple option values
      const result = await localServices.wpCliRun(
        siteId,
        ['eval', phpCode],
      );

      if (result.success) {
        try {
          const verified = JSON.parse((result.stdout ?? '').trim());

          // Check if all options were successfully written
          const allEnabled = Object.values(verified).every(v => v === true);
          const enabledCount = Object.values(verified).filter(v => v === true).length;

          if (allEnabled) {
            aiFeatures = 'enabled';
            logger.info(`${tag} Verified: All AI features enabled (global + ${AI_EXPERIMENT_IDS.length} individual features) on site ${siteId}`);
          } else {
            // Partial success - some options didn't stick
            const failed = Object.keys(verified).filter(k => verified[k] !== true);
            logger.error(`${tag} Partial enable: ${enabledCount}/${Object.keys(verified).length} features enabled. Failed: ${failed.join(', ')}`);
            aiFeatures = enabledCount > 0 ? 'enabled' : 'failed';
          }
        } catch {
          // Got stdout but couldn't parse — assume success if command succeeded
          logger.error(`${tag} Could not verify AI features - assuming success based on wp-cli exit code`);
          aiFeatures = 'enabled';
        }
      } else {
        throw new Error(result.stdout ?? 'Unknown error');
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`${tag} AI features step failed: ${redactCredentials(msg)}`);
      aiFeatures = 'failed';
    }
  }

  // Step 4: Sync credentials
  let credentials: SetupAIResult['credentials'] = 'skipped';

  if (configuredProviders.length > 0 && aiPlugin !== 'failed') {
    try {
      const entries: CredentialEntry[] = configuredProviders.map((provider) => ({
        provider,
        key: storedKeys[provider],
        optionName: PROVIDER_TO_WP_OPTION[provider],
      }));

      const phpCode = buildCredentialSyncPhp(entries);
      // skipPlugins defaults to true — safe because we remove all filters and verify via $wpdb
      const result = await localServices.wpCliRun(
        siteId,
        ['eval', phpCode],
      );

      if (result.success) {
        credentials = 'synced';
        logger.info(`${tag} Synced ${configuredProviders.length} credential(s) to site ${siteId}`);
      } else {
        throw new Error(result.stdout ?? 'Unknown error');
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`${tag} Credential sync step failed: ${redactCredentials(msg)}`);
      credentials = 'failed';
    }
  }

  // Step 5: Handle ACF abilities mu-plugin (only if ACF PRO is already installed)
  // Refresh plugin list to check for ACF PRO
  try {
    plugins = await localServices.getPlugins(siteId);
  } catch {
    // Continue with stale plugin list
  }
  let acfAbilities: SetupAIResult['acfAbilities'] = 'skipped';
  const acfPlugin = findPlugin(plugins, 'advanced-custom-fields-pro');

  if (acfPlugin && acfPlugin.status === 'active' && meetsMinVersion(acfPlugin.version, 6, 8)) {
    try {
      // Check if mu-plugin already exists
      const checkPhp = `echo file_exists(WPMU_PLUGIN_DIR . '/${ACF_MU_PLUGIN_FILENAME}') ? 'exists' : 'missing';`;
      const checkResult = await localServices.wpCliRun(siteId, ['eval', checkPhp]);

      if (checkResult.success && checkResult.stdout?.trim() === 'exists') {
        acfAbilities = 'already_enabled';
      } else {
        // Write the mu-plugin
        logger.info(`${tag} Writing ACF abilities mu-plugin on site ${siteId}`);
        const phpContent = ACF_MU_PLUGIN_CONTENT.replace(/'/g, "\\'");
        const writePhp = [
          `$dir = WPMU_PLUGIN_DIR;`,
          `if (!is_dir($dir)) { wp_mkdir_p($dir); }`,
          `$file = $dir . '/${ACF_MU_PLUGIN_FILENAME}';`,
          `$content = '${phpContent}';`,
          `$written = file_put_contents($file, $content);`,
          `echo $written !== false ? 'ok' : 'fail';`,
        ].join(' ');

        const writeResult = await localServices.wpCliRun(siteId, ['eval', writePhp]);
        if (writeResult.success && writeResult.stdout?.trim() === 'ok') {
          acfAbilities = 'enabled';
        } else {
          throw new Error(writeResult.stdout ?? 'Failed to write mu-plugin');
        }
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`${tag} ACF abilities step failed: ${redactCredentials(msg)}`);
      acfAbilities = 'failed';
    }
  }

  // Build result
  const success = aiPlugin !== 'failed';
  const parts: string[] = [];

  switch (aiPlugin) {
    case 'installed': parts.push('AI Experiments plugin installed and activated'); break;
    case 'activated': parts.push('AI Experiments plugin activated'); break;
    case 'already_active': parts.push('AI Experiments plugin already active'); break;
    case 'failed': parts.push('AI Experiments plugin setup failed'); break;
  }

  switch (connectorPlugin) {
    case 'installed': parts.push('Nexus AI Connector plugin installed'); break;
    case 'already_active': parts.push('Nexus AI Connector plugin already active'); break;
    case 'skipped': break;
    case 'failed': parts.push('Nexus AI Connector plugin failed'); break;
  }

  switch (providerPlugins) {
    case 'installed': parts.push('AI provider plugin(s) installed'); break;
    case 'already_active': parts.push('AI provider plugin(s) already active'); break;
    case 'skipped': break;
    case 'failed': parts.push('AI provider plugin installation failed'); break;
  }

  switch (gatewayProvider) {
    case 'installed': parts.push('Local Gateway provider installed'); break;
    case 'activated': parts.push('Local Gateway provider activated'); break;
    case 'already_active': parts.push('Local Gateway provider already active'); break;
    case 'skipped': break;
    case 'failed': parts.push('Local Gateway provider failed'); break;
  }

  switch (ollamaProvider) {
    case 'installed': parts.push('Ollama provider plugin installed'); break;
    case 'activated': parts.push('Ollama provider plugin activated'); break;
    case 'already_active': parts.push('Ollama provider plugin already active'); break;
    case 'skipped': break;
    case 'failed': parts.push('Ollama provider plugin failed'); break;
  }

  switch (aiFeatures) {
    case 'enabled': parts.push('All AI experiments enabled'); break;
    case 'skipped': break; // Don't clutter message if skipped due to plugin failure
    case 'failed': parts.push('AI experiment enablement failed'); break;
  }

  switch (credentials) {
    case 'synced': parts.push(`${configuredProviders.length} API key(s) synced`); break;
    case 'skipped': parts.push('No API keys configured to sync'); break;
    case 'failed': parts.push('Credential sync failed'); break;
  }

  switch (acfAbilities) {
    case 'enabled': parts.push('ACF abilities mu-plugin created'); break;
    case 'already_enabled': parts.push('ACF abilities mu-plugin already present'); break;
    case 'skipped': parts.push('ACF abilities skipped (ACF PRO >= 6.8 not found)'); break;
    case 'failed': parts.push('ACF abilities mu-plugin failed'); break;
  }

  const message = parts.join('. ') + '.';
  logger.info(`${tag} Result for site ${siteId}: ${message}`);

  return {
    success,
    aiPlugin,
    connectorPlugin,
    providerPlugins,
    gatewayProvider,
    ollamaProvider,
    aiFeatures,
    credentials,
    acfAbilities,
    message,
  };
}
