/**
 * Setup Site for AI
 *
 * Installs the AI Experiments plugin and optionally writes the ACF abilities
 * mu-plugin for sites with ACF PRO >= 6.8. Called via IPC from the UI,
 * not exposed as an MCP tool.
 */
import type { LocalServicesBridge, WpPlugin } from '../../local-services-bridge';

export interface SetupAIResult {
  success: boolean;
  aiPlugin: 'installed' | 'activated' | 'already_active' | 'failed';
  acfAbilities: 'enabled' | 'already_enabled' | 'skipped' | 'failed';
  message: string;
}

interface Logger {
  info(...args: unknown[]): void;
  error(...args: unknown[]): void;
}

const ACF_MU_PLUGIN_FILENAME = 'enable-acf-abilities.php';

/**
 * PHP content for the ACF abilities mu-plugin.
 * Opts ACF PRO into the WordPress Abilities API.
 */
const ACF_MU_PLUGIN_CONTENT = `<?php
/**
 * Plugin Name: Enable ACF Abilities
 * Description: Opts ACF PRO into the WordPress Abilities API for AI tooling.
 * Version: 1.0.0
 * Auto-generated by Nexus AI.
 */
add_filter('acf/abilities/enabled', '__return_true');
`;

function findPlugin(plugins: WpPlugin[], slug: string): WpPlugin | undefined {
  return plugins.find((p) => p.name === slug);
}

function meetsMinVersion(version: string, minMajor: number, minMinor: number): boolean {
  const parts = version.split('.');
  const major = parseInt(parts[0], 10);
  const minor = parseInt(parts[1] ?? '0', 10);
  if (isNaN(major)) return false;
  return major > minMajor || (major === minMajor && minor >= minMinor);
}

export async function setupSiteForAI(
  siteId: string,
  localServices: LocalServicesBridge,
  logger: Logger,
): Promise<SetupAIResult> {
  const tag = '[NexusAI:setup-ai]';

  // Step 1: Get current plugin list
  let plugins: WpPlugin[];
  try {
    plugins = await localServices.getPlugins(siteId);
  } catch (err) {
    const msg = `Failed to list plugins: ${err instanceof Error ? err.message : String(err)}`;
    logger.error(tag, msg);
    return { success: false, aiPlugin: 'failed', acfAbilities: 'failed', message: msg };
  }

  // Step 2: Handle AI Experiments plugin ("ai")
  let aiPlugin: SetupAIResult['aiPlugin'] = 'failed';
  const existingAi = findPlugin(plugins, 'ai');

  try {
    if (!existingAi) {
      // Not installed — install and activate
      logger.info(tag, `Installing AI Experiments plugin on site ${siteId}`);
      const result = await localServices.wpCliRun(siteId, ['plugin', 'install', 'ai', '--activate']);
      if (!result.success) {
        throw new Error(result.stdout ?? 'Unknown error');
      }
      aiPlugin = 'installed';
    } else if (existingAi.status !== 'active') {
      // Installed but inactive — activate
      logger.info(tag, `Activating AI Experiments plugin on site ${siteId}`);
      const result = await localServices.wpCliRun(siteId, ['plugin', 'activate', 'ai']);
      if (!result.success) {
        throw new Error(result.stdout ?? 'Unknown error');
      }
      aiPlugin = 'activated';
    } else {
      // Already active
      aiPlugin = 'already_active';
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(tag, `AI plugin step failed: ${msg}`);
    aiPlugin = 'failed';
  }

  // Step 3: Handle ACF abilities mu-plugin
  let acfAbilities: SetupAIResult['acfAbilities'] = 'skipped';
  const acfPlugin = findPlugin(plugins, 'advanced-custom-fields-pro');

  if (acfPlugin && acfPlugin.status === 'active' && meetsMinVersion(acfPlugin.version, 6, 8)) {
    try {
      // Check if mu-plugin already exists
      const checkPhp = `echo file_exists(WPMU_PLUGIN_DIR . '/${ACF_MU_PLUGIN_FILENAME}') ? 'exists' : 'missing';`;
      const checkResult = await localServices.wpCliRun(siteId, ['eval', checkPhp]);

      if (checkResult.success && checkResult.stdout?.trim() === 'exists') {
        acfAbilities = 'already_enabled';
      } else {
        // Write the mu-plugin
        logger.info(tag, `Writing ACF abilities mu-plugin on site ${siteId}`);
        const phpContent = ACF_MU_PLUGIN_CONTENT.replace(/'/g, "\\'");
        const writePhp = [
          `$dir = WPMU_PLUGIN_DIR;`,
          `if (!is_dir($dir)) { wp_mkdir_p($dir); }`,
          `$file = $dir . '/${ACF_MU_PLUGIN_FILENAME}';`,
          `$content = '${phpContent}';`,
          `$written = file_put_contents($file, $content);`,
          `echo $written !== false ? 'ok' : 'fail';`,
        ].join(' ');

        const writeResult = await localServices.wpCliRun(siteId, ['eval', writePhp]);
        if (writeResult.success && writeResult.stdout?.trim() === 'ok') {
          acfAbilities = 'enabled';
        } else {
          throw new Error(writeResult.stdout ?? 'Failed to write mu-plugin');
        }
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(tag, `ACF abilities step failed: ${msg}`);
      acfAbilities = 'failed';
    }
  }

  // Build result
  const success = aiPlugin !== 'failed';
  const parts: string[] = [];

  switch (aiPlugin) {
    case 'installed': parts.push('AI Experiments plugin installed and activated'); break;
    case 'activated': parts.push('AI Experiments plugin activated'); break;
    case 'already_active': parts.push('AI Experiments plugin already active'); break;
    case 'failed': parts.push('AI Experiments plugin setup failed'); break;
  }

  switch (acfAbilities) {
    case 'enabled': parts.push('ACF abilities mu-plugin created'); break;
    case 'already_enabled': parts.push('ACF abilities mu-plugin already present'); break;
    case 'skipped': parts.push('ACF abilities skipped (ACF PRO >= 6.8 not found)'); break;
    case 'failed': parts.push('ACF abilities mu-plugin failed'); break;
  }

  return {
    success,
    aiPlugin,
    acfAbilities,
    message: parts.join('. ') + '.',
  };
}
