/**
 * Tests for AIContextGenerator
 */

import { AIContextGenerator } from '../../../src/main/ai-context/AIContextGenerator';
import type { AIContextData } from '../../../src/main/ai-context/AIContextGenerator';

describe('AIContextGenerator', () => {
  let generator: AIContextGenerator;

  beforeEach(() => {
    generator = new AIContextGenerator();
  });

  describe('generateContext', () => {
    it('should generate minimal context with just site info', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('# AI Development Context - test-site');
      expect(result).toContain('## WordPress Environment');
      expect(result).toContain('http://test-site.local');
      expect(result).toContain('http://test-site.local/wp-admin');
      expect(result).toContain('## File Structure');
      expect(result).toContain('## Development Guidelines');
      expect(result).toContain('auto-generated by Local AI Nexus');
      expect(result).toContain('Edit with caution');
    });

    it('should include WordPress version and PHP version', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        wpVersion: '7.0-beta6-62094',
        phpVersion: '8.3.13',
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('WordPress Version:** 7.0-beta6-62094');
      expect(result).toContain('PHP Version:** 8.3.13');
    });

    it('should include MySQL port', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        mysqlPort: 10003,
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('MySQL:** localhost:10003 (root/root)');
    });

    it('should list active plugins', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        plugins: [
          { name: 'ai', title: 'AI', version: '0.6.0', status: 'active' },
          {
            name: 'advanced-custom-fields-pro',
            title: 'Advanced Custom Fields PRO',
            version: '7.0.0',
            status: 'active',
          },
          { name: 'inactive-plugin', title: 'Inactive', version: '1.0', status: 'inactive' },
        ],
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('## Active Plugins');
      expect(result).toContain('**AI** (v0.6.0)');
      expect(result).toContain('**Advanced Custom Fields PRO** (v7.0.0)');
      expect(result).not.toContain('Inactive');
    });

    it('should show active theme', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        theme: {
          name: 'twentytwentyfour',
          title: 'Twenty Twenty-Four',
          version: '1.0',
        },
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('## Active Theme');
      expect(result).toContain('**Twenty Twenty-Four** (v1.0)');
    });

    it('should include AI Gateway configuration', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        aiGateway: {
          url: 'http://127.0.0.1:13000/ai-gateway/v1',
          token: '10177933-3caf-4c72-8a28-5238bbb70e20',
          models: ['Claude Haiku 4.5', 'Claude Sonnet 4.5'],
        },
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('## AI Configuration');
      expect(result).toContain('http://127.0.0.1:13000/ai-gateway/v1');
      expect(result).toContain('Claude Haiku 4.5, Claude Sonnet 4.5');
      expect(result).toContain('nexus-ai-connector-config.php');
      expect(result).toContain('Local AI Gateway for tracking');
    });

    it('should mask AI Gateway token', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        aiGateway: {
          url: 'http://127.0.0.1:13000/ai-gateway/v1',
          token: '10177933-3caf-4c72-8a28-5238bbb70e20',
          models: [],
        },
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      // Should show first 8 chars, mask middle, show last 4 chars of UUID
      expect(result).toContain('10177933-****-****-****-********0e20');
      // Should not expose the middle sections
      expect(result).not.toContain('3caf');
      expect(result).not.toContain('4c72');
      expect(result).not.toContain('8a28');
      expect(result).not.toContain('5238bbb7');
    });

    it('should include AI integration guidelines when AI configured', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        aiGateway: {
          url: 'http://127.0.0.1:13000/ai-gateway/v1',
          token: 'test-token',
          models: [],
        },
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('### AI Integration');
      expect(result).toContain('wp_ai_generate_text()');
      expect(result).toContain('route through Local Gateway');
    });

    it('should omit AI integration guidelines when AI not configured', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).not.toContain('### AI Integration');
      expect(result).not.toContain('wp_ai_generate_text()');
    });

    it('should mention ACF if installed', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        plugins: [
          {
            name: 'advanced-custom-fields-pro',
            title: 'Advanced Custom Fields PRO',
            version: '7.0.0',
            status: 'active',
          },
        ],
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('**ACF Pro available**');
    });

    it('should include common WP-CLI commands', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('## Common Commands');
      expect(result).toContain('wp plugin list');
      expect(result).toContain('wp db query');
      expect(result).toContain('wp eval');
      expect(result).toContain('wp user create');
    });

    it('should include debugging section with MySQL port', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        mysqlPort: 10005,
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('## Debugging');
      expect(result).toContain('/wp-content/debug.log');
      expect(result).toContain('localhost:10005, root/root');
      expect(result).toContain('View in Local app');
    });

    it('should use default MySQL port 3306 if not specified', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      expect(result).toContain('localhost:3306');
    });

    it('should format generation date correctly', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        generatedAt: new Date('2026-03-24T12:00:00Z').getTime(),
      };

      const result = generator.generateContext(data);

      // Date format may vary by locale, just check it contains March and 2026
      expect(result).toContain('March');
      expect(result).toContain('2026');
    });

    it('should sort plugins alphabetically by title', () => {
      const data: AIContextData = {
        siteName: 'test-site',
        siteUrl: 'http://test-site.local',
        sitePath: '/Users/test/Local Sites/test-site/app/public',
        plugins: [
          { name: 'z-plugin', title: 'Zebra Plugin', version: '1.0', status: 'active' },
          { name: 'a-plugin', title: 'Aardvark Plugin', version: '1.0', status: 'active' },
          { name: 'm-plugin', title: 'Monkey Plugin', version: '1.0', status: 'active' },
        ],
        generatedAt: Date.now(),
      };

      const result = generator.generateContext(data);

      const aardvarkIndex = result.indexOf('Aardvark');
      const monkeyIndex = result.indexOf('Monkey');
      const zebraIndex = result.indexOf('Zebra');

      expect(aardvarkIndex).toBeLessThan(monkeyIndex);
      expect(monkeyIndex).toBeLessThan(zebraIndex);
    });
  });
});
