/**
 * Docker sshd fixture: one container, two WordPress installs, one alias.
 *
 * The alias must resolve through the developer's REAL ~/.ssh/config, because
 * buildExternalSshArgs passes no -F and has no override (that is deliberate —
 * -F /dev/null would break ProxyJump). So this writes a block to
 * ~/.ssh/config.d/nexus-e2e and one Include line, mirroring what the shipped
 * sshConfigWriter.ts does, and removes both at teardown.
 *
 * It NEVER touches ~/.ssh/config.d/nexus, which is the real writer's file.
 */
import { execFileSync, execFile } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const execFileAsync = promisify(execFile);

export const FIXTURE_ALIAS = 'nexus-e2e-host';
export const FIXTURE_SITES = ['alpha', 'beta'] as const;
export const FIXTURE_PORT = 2222;
export const FIXTURE_HOST = '127.0.0.1';

const FIXTURE_DIR = path.resolve(__dirname, '..', 'fixtures', 'ssh-host');
const KEY_PATH = path.join(FIXTURE_DIR, 'id_ed25519');
const SSH_DIR = path.join(os.homedir(), '.ssh');
const CONFIG_PATH = path.join(SSH_DIR, 'config');
const NEXUS_E2E_CONFIG = path.join(SSH_DIR, 'config.d', 'nexus-e2e');
const INCLUDE_LINE = 'Include ~/.ssh/config.d/nexus-e2e';
const KNOWN_HOSTS_ENTRY = `[${FIXTURE_HOST}]:${FIXTURE_PORT}`;

function compose(args: string[], timeout = 300_000): string {
  return execFileSync('docker', ['compose', ...args], {
    cwd: FIXTURE_DIR, encoding: 'utf8', timeout,
  });
}

export function fixtureAvailable(): boolean {
  return process.env.CLI_E2E_SSH_FIXTURE === 'ready';
}

function dockerReachable(): boolean {
  try {
    execFileSync('docker', ['info', '--format', '{{.ServerVersion}}'],
      { stdio: 'ignore', timeout: 10_000 });
    return true;
  } catch { return false; }
}

function ensureKeypair(): void {
  if (fs.existsSync(KEY_PATH)) return;
  execFileSync('ssh-keygen', ['-t', 'ed25519', '-N', '', '-C', 'nexus-e2e', '-f', KEY_PATH]);
}

function writeAliasBlock(): void {
  fs.mkdirSync(path.join(SSH_DIR, 'config.d'), { recursive: true });
  fs.writeFileSync(NEXUS_E2E_CONFIG,
    `# Generated by the Nexus E2E SSH fixture. Removed at teardown.\n` +
    `Host ${FIXTURE_ALIAS}\n` +
    `  HostName ${FIXTURE_HOST}\n` +
    `  Port ${FIXTURE_PORT}\n` +
    `  User wp\n` +
    `  IdentityFile ${KEY_PATH}\n` +
    `  IdentitiesOnly yes\n`,
    { mode: 0o600 });

  // Idempotent Include at the TOP: ssh_config is first-obtained-value-wins.
  const existing = fs.existsSync(CONFIG_PATH) ? fs.readFileSync(CONFIG_PATH, 'utf8') : '';
  if (!existing.split('\n').some((l) => l.trim() === INCLUDE_LINE)) {
    fs.writeFileSync(CONFIG_PATH, `${INCLUDE_LINE}\n${existing}`, { mode: 0o600 });
  }
}

function removeAliasBlock(): void {
  try { fs.unlinkSync(NEXUS_E2E_CONFIG); } catch { /* already gone */ }
  if (!fs.existsSync(CONFIG_PATH)) return;
  const kept = fs.readFileSync(CONFIG_PATH, 'utf8')
    .split('\n').filter((l) => l.trim() !== INCLUDE_LINE).join('\n');
  fs.writeFileSync(CONFIG_PATH, kept, { mode: 0o600 });
}

async function installAuthorizedKey(): Promise<void> {
  const pub = fs.readFileSync(`${KEY_PATH}.pub`, 'utf8').trim();
  compose(['exec', '-T', 'sshhost', 'bash', '-c',
    `mkdir -p /home/wp/.ssh && echo '${pub}' > /home/wp/.ssh/authorized_keys ` +
    `&& chown -R wp:wp /home/wp/.ssh && chmod 700 /home/wp/.ssh ` +
    `&& chmod 600 /home/wp/.ssh/authorized_keys`]);
}

/**
 * Read the container's host key directly rather than ssh-keyscan: deterministic,
 * no network race, and it keeps the fixture honest about the product rule that
 * ssh-keyscan is never the right tool (it cannot traverse a ProxyJump).
 */
export async function trustFixtureHostKey(): Promise<void> {
  const pub = compose(['exec', '-T', 'sshhost', 'cat', '/etc/ssh/ssh_host_ed25519_key.pub']).trim();
  const [type, b64] = pub.split(/\s+/);
  await forgetFixtureHostKey();
  fs.appendFileSync(path.join(SSH_DIR, 'known_hosts'), `${KNOWN_HOSTS_ENTRY} ${type} ${b64}\n`);
}

export async function forgetFixtureHostKey(): Promise<void> {
  try {
    await execFileAsync('ssh-keygen', ['-R', KNOWN_HOSTS_ENTRY], { timeout: 10_000 });
  } catch { /* absent is fine */ }
}

/** Turn a trusted host into a host-key-changed host. */
export async function rotateFixtureHostKey(): Promise<void> {
  compose(['exec', '-T', 'sshhost', 'bash', '-c',
    'rm -f /etc/ssh/ssh_host_* && ssh-keygen -A && pkill -HUP sshd || true']);
  compose(['restart', 'sshhost']);
  await waitForSsh();
}

/**
 * Shared hosting commonly sets disable_functions=proc_open, which makes
 * `wp --info` fail and php_version permanently NULL. Runtime toggle, same
 * container — not a second image.
 */
export async function setProcOpenDisabled(disabled: boolean): Promise<void> {
  const ini = '/usr/local/etc/php/conf.d/zz-nexus-e2e-procopen.ini';
  compose(['exec', '-T', 'sshhost', 'bash', '-c', disabled
    ? `echo 'disable_functions=proc_open,proc_close' > ${ini}`
    : `rm -f ${ini}`]);
}

async function waitForSsh(timeoutMs = 60_000): Promise<void> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    try {
      await execFileAsync('ssh', [
        '-o', 'StrictHostKeyChecking=no',
        '-o', `UserKnownHostsFile=${path.join(FIXTURE_DIR, '.probe_known_hosts')}`,
        '-o', 'BatchMode=yes', '-i', KEY_PATH,
        '-p', String(FIXTURE_PORT), `wp@${FIXTURE_HOST}`, 'echo ready',
      ], { timeout: 10_000 });
      return;
    } catch { await new Promise((r) => setTimeout(r, 2000)); }
  }
  throw new Error(`SSH fixture did not accept connections within ${timeoutMs}ms`);
}

export async function startSshFixture(): Promise<boolean> {
  if (!dockerReachable()) return false;
  ensureKeypair();
  compose(['up', '-d', '--build']);
  await installAuthorizedKey();
  await waitForSsh();
  writeAliasBlock();
  process.env.CLI_E2E_SSH_FIXTURE = 'ready';
  return true;
}

/**
 * Hard-delete fixture-owned rows from graph.db so "unrefreshed" is real.
 *
 * DANGER: The developer has four REAL external hosts in this same table:
 * hostinger-test, piedmontdermgroup, willowcreekderm, tablemesaderm. A widened
 * predicate would destroy their data. The alias guard below makes it structurally
 * impossible to widen: the prefix is derived from FIXTURE_ALIAS, we assert it
 * equals the literal 'nexus-e2e-host', and refuse to run otherwise.
 */
export async function resetFixtureGraphState(): Promise<void> {
  if (FIXTURE_ALIAS !== 'nexus-e2e-host') {
    throw new Error(`resetFixtureGraphState guard: FIXTURE_ALIAS must be 'nexus-e2e-host', got '${FIXTURE_ALIAS}'`);
  }

  const dbPath = path.join(os.homedir(), 'Library', 'Application Support', 'Local', 'nexus-ai', 'graph.db');
  const prefix = `ssh:${FIXTURE_ALIAS}`;

  // Use /usr/bin/sqlite3 (NOT better-sqlite3 from the test process — it's compiled
  // for Electron's ABI and will throw NODE_MODULE_VERSION in jest). DB is in WAL
  // mode, so writing while Local holds it open is safe.
  const sql = `
    DELETE FROM content WHERE site_id LIKE '${prefix}%';
    DELETE FROM themes WHERE site_id IN (SELECT id FROM sites WHERE id LIKE '${prefix}%');
    DELETE FROM plugins WHERE site_id IN (SELECT id FROM sites WHERE id LIKE '${prefix}%');
    DELETE FROM sites WHERE id LIKE '${prefix}%';
  `;

  execFileSync('/usr/bin/sqlite3', [dbPath, sql], { encoding: 'utf8', timeout: 30_000 });
}

/**
 * Clear php_version for fixture sites, modeling the batch-loss scenario where
 * plugins populate but the version does not. Same guard as resetFixtureGraphState.
 */
export async function clearFixturePhpVersion(): Promise<void> {
  if (FIXTURE_ALIAS !== 'nexus-e2e-host') {
    throw new Error(`clearFixturePhpVersion guard: FIXTURE_ALIAS must be 'nexus-e2e-host', got '${FIXTURE_ALIAS}'`);
  }

  const dbPath = path.join(os.homedir(), 'Library', 'Application Support', 'Local', 'nexus-ai', 'graph.db');
  const prefix = `ssh:${FIXTURE_ALIAS}`;
  const sql = `UPDATE sites SET php_version = NULL WHERE id LIKE '${prefix}%';`;

  execFileSync('/usr/bin/sqlite3', [dbPath, sql], { encoding: 'utf8', timeout: 30_000 });
}

export async function stopSshFixture(): Promise<void> {
  // Remove the graph registration. Lives here rather than in each test file's
  // afterAll because all six test files (27-32) register this host, so a
  // per-file afterAll would be six identical blocks — and it would not run at
  // all if a file failed to load. Centralizing here ensures "remove every trace"
  // runs once from globalTeardown.
  try {
    const cliPath = path.resolve(__dirname, '../../../bin/nexus.js');
    if (FIXTURE_ALIAS !== 'nexus-e2e-host') {
      throw new Error(`FIXTURE_ALIAS guard: expected 'nexus-e2e-host', got '${FIXTURE_ALIAS}'`);
    }
    execFileSync('node', [cliPath, 'host', 'remove', FIXTURE_ALIAS, '-y'], {
      stdio: 'ignore', timeout: 30_000,
    });
  } catch (e: any) {
    // Best-effort: the CLI may be unreachable, or the host was never registered.
    // Log and continue to the SSH/container cleanup — teardown must never throw.
    console.warn(`[CLI E2E Teardown] Could not remove graph registration: ${e?.message ?? e}`);
  }

  removeAliasBlock();
  await forgetFixtureHostKey();
  try { fs.unlinkSync(path.join(FIXTURE_DIR, '.probe_known_hosts')); } catch { /* fine */ }
  try { compose(['down', '-v'], 120_000); } catch { /* already down */ }
  delete process.env.CLI_E2E_SSH_FIXTURE;
}
