// AUTO-GENERATED by `npm run generate:built-in-tools` — do not edit by hand.
// Drift gate: `npm run generate:built-in-tools:check` (exit 1 when out of date).
// Names come from the real registration path — the same register*Tools calls the app makes in
// src/main/index.ts — collected through a stub registry, sorted, deduplicated by the generator.

export type BuiltInTool =
  | 'ask_ollama'
  | 'bulk_plugin_update'
  | 'bulk_reindex'
  | 'clean_database_items'
  | 'clear_telemetry_events'
  | 'compare_sites'
  | 'describe_site_fields'
  | 'detect_drift'
  | 'find_outdated_sites'
  | 'find_sites_with_plugin'
  | 'find_sites_with_theme'
  | 'fleet_database_health'
  | 'fleet_filter'
  | 'fleet_health_summary'
  | 'fleet_overview'
  | 'fleet_search'
  | 'fleet_sql'
  | 'fleet_summary'
  | 'get_all_site_documents'
  | 'get_database_recommendations'
  | 'get_event_endpoint_info'
  | 'get_event_processor_stats'
  | 'get_gateway_usage'
  | 'get_graph_content'
  | 'get_graph_plugin'
  | 'get_graph_stats'
  | 'get_index_status'
  | 'get_metrics'
  | 'get_site_health'
  | 'get_site_structure'
  | 'get_system_health'
  | 'get_telemetry_status'
  | 'get_tool_metrics'
  | 'list_graph_content'
  | 'list_graph_plugins'
  | 'list_indexed_sites'
  | 'list_ollama_models'
  | 'list_site_groups'
  | 'local_change_php_version'
  | 'local_clone_site'
  | 'local_create_site'
  | 'local_delete_site'
  | 'local_export_site'
  | 'local_get_site'
  | 'local_get_site_changes'
  | 'local_get_site_logs'
  | 'local_get_sync_history'
  | 'local_import_site'
  | 'local_list_blueprints'
  | 'local_list_sites'
  | 'local_operation_status'
  | 'local_rename_site'
  | 'local_restart_site'
  | 'local_start_site'
  | 'local_stop_site'
  | 'local_toggle_xdebug'
  | 'local_trust_ssl'
  | 'local_wpe_link'
  | 'local_wpe_pull'
  | 'local_wpe_push'
  | 'manage_site_group'
  | 'nexus_fleet_list'
  | 'nexus_fleet_plugins'
  | 'nexus_fleet_refresh'
  | 'nexus_fleet_summary'
  | 'nexus_get_fleet_twins'
  | 'nexus_get_settings'
  | 'nexus_get_site_ai_config'
  | 'nexus_get_site_twin'
  | 'nexus_intelligence_health'
  | 'nexus_link_site'
  | 'nexus_list_sites'
  | 'nexus_load_procedure'
  | 'nexus_pairing_proposals'
  | 'nexus_plugin_audit'
  | 'nexus_rebuild_twins'
  | 'nexus_site_audit'
  | 'nexus_site_refresh'
  | 'nexus_site_status'
  | 'nexus_switch_provider'
  | 'nexus_sync_credentials'
  | 'nexus_unlink_site'
  | 'nexus_update_settings'
  | 'nexus_where_am_i'
  | 'reindex_site'
  | 'reset_metrics'
  | 'reset_telemetry'
  | 'scan_database_health'
  | 'scan_site_files'
  | 'search_across_sites'
  | 'search_site_content'
  | 'search_tools'
  | 'set_telemetry_enabled'
  | 'verify_site_live'
  | 'wp_core_update'
  | 'wp_core_version'
  | 'wp_db_export'
  | 'wp_eval'
  | 'wp_import_database'
  | 'wp_list_abilities'
  | 'wp_option_get'
  | 'wp_plugin_activate'
  | 'wp_plugin_deactivate'
  | 'wp_plugin_install'
  | 'wp_plugin_list'
  | 'wp_plugin_update'
  | 'wp_post_create'
  | 'wp_post_delete'
  | 'wp_post_update'
  | 'wp_run_ability'
  | 'wp_search_replace'
  | 'wp_setup_ai'
  | 'wp_site_health'
  | 'wp_sync_ai_credentials'
  | 'wp_theme_activate'
  | 'wp_theme_list'
  | 'wp_user_list'
  | 'wpe_account_domains'
  | 'wpe_account_overview'
  | 'wpe_account_ssl_status'
  | 'wpe_add_user_to_accounts'
  | 'wpe_backup_and_verify'
  | 'wpe_check_domain_status'
  | 'wpe_create_account_user'
  | 'wpe_create_backup'
  | 'wpe_create_domain'
  | 'wpe_create_domains_bulk'
  | 'wpe_create_install'
  | 'wpe_create_site'
  | 'wpe_create_ssh_key'
  | 'wpe_delete_account_user'
  | 'wpe_delete_domain'
  | 'wpe_delete_install'
  | 'wpe_delete_site'
  | 'wpe_delete_ssh_key'
  | 'wpe_detect_drift'
  | 'wpe_diagnose_site'
  | 'wpe_environment_diff'
  | 'wpe_fleet_health'
  | 'wpe_fleet_versions'
  | 'wpe_get_account'
  | 'wpe_get_account_limits'
  | 'wpe_get_account_usage'
  | 'wpe_get_account_usage_insights'
  | 'wpe_get_account_usage_summary'
  | 'wpe_get_account_user'
  | 'wpe_get_account_users'
  | 'wpe_get_accounts'
  | 'wpe_get_backup'
  | 'wpe_get_current_user'
  | 'wpe_get_domain'
  | 'wpe_get_domain_ssl_certificate'
  | 'wpe_get_domain_status_report'
  | 'wpe_get_domains'
  | 'wpe_get_install'
  | 'wpe_get_install_usage'
  | 'wpe_get_installs'
  | 'wpe_get_largefs_validation'
  | 'wpe_get_offload_settings'
  | 'wpe_get_site'
  | 'wpe_get_sites'
  | 'wpe_get_ssh_keys'
  | 'wpe_get_ssl_certificates'
  | 'wpe_go_live_checklist'
  | 'wpe_import_ssl_certificate'
  | 'wpe_installs_by_account'
  | 'wpe_login'
  | 'wpe_logout'
  | 'wpe_portfolio_overview'
  | 'wpe_portfolio_usage'
  | 'wpe_prepare_go_live'
  | 'wpe_promote_environment'
  | 'wpe_purge_cache'
  | 'wpe_refresh_account_disk_usage'
  | 'wpe_refresh_install_disk_usage'
  | 'wpe_request_ssl_certificate'
  | 'wpe_site_deep_refresh'
  | 'wpe_status'
  | 'wpe_sync_sites'
  | 'wpe_update_account_user'
  | 'wpe_update_domain'
  | 'wpe_update_install'
  | 'wpe_update_offload_settings'
  | 'wpe_update_site'
  | 'wpe_user_audit'
  | 'wpe_wait_for_ssh';

export const BUILT_IN_TOOL_NAMES = [
  'ask_ollama',
  'bulk_plugin_update',
  'bulk_reindex',
  'clean_database_items',
  'clear_telemetry_events',
  'compare_sites',
  'describe_site_fields',
  'detect_drift',
  'find_outdated_sites',
  'find_sites_with_plugin',
  'find_sites_with_theme',
  'fleet_database_health',
  'fleet_filter',
  'fleet_health_summary',
  'fleet_overview',
  'fleet_search',
  'fleet_sql',
  'fleet_summary',
  'get_all_site_documents',
  'get_database_recommendations',
  'get_event_endpoint_info',
  'get_event_processor_stats',
  'get_gateway_usage',
  'get_graph_content',
  'get_graph_plugin',
  'get_graph_stats',
  'get_index_status',
  'get_metrics',
  'get_site_health',
  'get_site_structure',
  'get_system_health',
  'get_telemetry_status',
  'get_tool_metrics',
  'list_graph_content',
  'list_graph_plugins',
  'list_indexed_sites',
  'list_ollama_models',
  'list_site_groups',
  'local_change_php_version',
  'local_clone_site',
  'local_create_site',
  'local_delete_site',
  'local_export_site',
  'local_get_site',
  'local_get_site_changes',
  'local_get_site_logs',
  'local_get_sync_history',
  'local_import_site',
  'local_list_blueprints',
  'local_list_sites',
  'local_operation_status',
  'local_rename_site',
  'local_restart_site',
  'local_start_site',
  'local_stop_site',
  'local_toggle_xdebug',
  'local_trust_ssl',
  'local_wpe_link',
  'local_wpe_pull',
  'local_wpe_push',
  'manage_site_group',
  'nexus_fleet_list',
  'nexus_fleet_plugins',
  'nexus_fleet_refresh',
  'nexus_fleet_summary',
  'nexus_get_fleet_twins',
  'nexus_get_settings',
  'nexus_get_site_ai_config',
  'nexus_get_site_twin',
  'nexus_intelligence_health',
  'nexus_link_site',
  'nexus_list_sites',
  'nexus_load_procedure',
  'nexus_pairing_proposals',
  'nexus_plugin_audit',
  'nexus_rebuild_twins',
  'nexus_site_audit',
  'nexus_site_refresh',
  'nexus_site_status',
  'nexus_switch_provider',
  'nexus_sync_credentials',
  'nexus_unlink_site',
  'nexus_update_settings',
  'nexus_where_am_i',
  'reindex_site',
  'reset_metrics',
  'reset_telemetry',
  'scan_database_health',
  'scan_site_files',
  'search_across_sites',
  'search_site_content',
  'search_tools',
  'set_telemetry_enabled',
  'verify_site_live',
  'wp_core_update',
  'wp_core_version',
  'wp_db_export',
  'wp_eval',
  'wp_import_database',
  'wp_list_abilities',
  'wp_option_get',
  'wp_plugin_activate',
  'wp_plugin_deactivate',
  'wp_plugin_install',
  'wp_plugin_list',
  'wp_plugin_update',
  'wp_post_create',
  'wp_post_delete',
  'wp_post_update',
  'wp_run_ability',
  'wp_search_replace',
  'wp_setup_ai',
  'wp_site_health',
  'wp_sync_ai_credentials',
  'wp_theme_activate',
  'wp_theme_list',
  'wp_user_list',
  'wpe_account_domains',
  'wpe_account_overview',
  'wpe_account_ssl_status',
  'wpe_add_user_to_accounts',
  'wpe_backup_and_verify',
  'wpe_check_domain_status',
  'wpe_create_account_user',
  'wpe_create_backup',
  'wpe_create_domain',
  'wpe_create_domains_bulk',
  'wpe_create_install',
  'wpe_create_site',
  'wpe_create_ssh_key',
  'wpe_delete_account_user',
  'wpe_delete_domain',
  'wpe_delete_install',
  'wpe_delete_site',
  'wpe_delete_ssh_key',
  'wpe_detect_drift',
  'wpe_diagnose_site',
  'wpe_environment_diff',
  'wpe_fleet_health',
  'wpe_fleet_versions',
  'wpe_get_account',
  'wpe_get_account_limits',
  'wpe_get_account_usage',
  'wpe_get_account_usage_insights',
  'wpe_get_account_usage_summary',
  'wpe_get_account_user',
  'wpe_get_account_users',
  'wpe_get_accounts',
  'wpe_get_backup',
  'wpe_get_current_user',
  'wpe_get_domain',
  'wpe_get_domain_ssl_certificate',
  'wpe_get_domain_status_report',
  'wpe_get_domains',
  'wpe_get_install',
  'wpe_get_install_usage',
  'wpe_get_installs',
  'wpe_get_largefs_validation',
  'wpe_get_offload_settings',
  'wpe_get_site',
  'wpe_get_sites',
  'wpe_get_ssh_keys',
  'wpe_get_ssl_certificates',
  'wpe_go_live_checklist',
  'wpe_import_ssl_certificate',
  'wpe_installs_by_account',
  'wpe_login',
  'wpe_logout',
  'wpe_portfolio_overview',
  'wpe_portfolio_usage',
  'wpe_prepare_go_live',
  'wpe_promote_environment',
  'wpe_purge_cache',
  'wpe_refresh_account_disk_usage',
  'wpe_refresh_install_disk_usage',
  'wpe_request_ssl_certificate',
  'wpe_site_deep_refresh',
  'wpe_status',
  'wpe_sync_sites',
  'wpe_update_account_user',
  'wpe_update_domain',
  'wpe_update_install',
  'wpe_update_offload_settings',
  'wpe_update_site',
  'wpe_user_audit',
  'wpe_wait_for_ssh',
] as const;
