import { afterEach, describe, expect, it, jest } from '@jest/globals';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { handleAgentToolsBuild } from '../../../src/cli/commands/agent';

describe('nexus agent tools build annotated manifests', () => {
  const temporaryDirectories: string[] = [];

  afterEach(() => {
    jest.restoreAllMocks();
    for (const directory of temporaryDirectories.splice(0)) {
      fs.rmSync(directory, { recursive: true, force: true });
    }
  });

  it('preserves the header, is idempotent, and checks only generated tool drift', async () => {
    const agentDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nexus-manifest-comments-'));
    temporaryDirectories.push(agentDir);

    fs.writeFileSync(
      path.join(agentDir, 'agent.js'),
      `module.exports = { default: {
        name: 'annotated-agent',
        version: '1.0.0',
        tools: ['wp_eval'],
        contributes: { tools: {
          inspect: {
            description: 'Inspect the site',
            inputSchema: { type: 'object', properties: { site: { type: 'string' } } }
          }
        } }
      } };`,
      'utf8',
    );

    const header =
      '# Maintained by the platform team. Keep this note exactly as written.\n' +
      '# Review tool permission changes with Security.\n' +
      '# AUTO-GENERATED by nexus agent tools build — generated fields follow\n';
    fs.writeFileSync(
      path.join(agentDir, 'nexus.agent.yaml'),
      header +
        yaml.dump({
          name: 'annotated-agent',
          version: '1.0.0',
          tools: ['stale_tool'],
          contributes: { tools: [] },
        }),
      'utf8',
    );

    await handleAgentToolsBuild(agentDir);

    const manifestPath = path.join(agentDir, 'nexus.agent.yaml');
    const firstBuild = fs.readFileSync(manifestPath, 'utf8');
    expect(firstBuild.slice(0, header.length)).toBe(header);
    expect(yaml.load(firstBuild)).toMatchObject({
      tools: ['wp_eval'],
      contributes: {
        tools: [{ name: 'inspect', description: 'Inspect the site' }],
      },
    });

    await handleAgentToolsBuild(agentDir);
    expect(fs.readFileSync(manifestPath, 'utf8')).toBe(firstBuild);
    await expect(handleAgentToolsBuild(agentDir, true)).resolves.toBeUndefined();

    const drifted = yaml.load(firstBuild.slice(header.length)) as Record<string, unknown>;
    drifted.tools = ['stale_tool'];
    fs.writeFileSync(manifestPath, header + yaml.dump(drifted), 'utf8');

    const exitSpy = jest.spyOn(process, 'exit').mockImplementation((() => {
      throw new Error('process.exit called');
    }) as never);
    await expect(handleAgentToolsBuild(agentDir, true)).rejects.toThrow('process.exit called');
    expect(exitSpy).toHaveBeenCalledWith(1);
  });
});
