/**
 * MU Plugin Template Generator
 *
 * Generates nexus-ai-connector-config.php MU plugin with:
 * - Webhook configuration
 * - AI Gateway configuration (if available)
 * - Automatic caller detection for AI request tracking
 */

export interface MuPluginConfig {
  webhookUrl: string;
  webhookAuthToken: string;
  siteId: string;
  aiGatewayUrl?: string;
  aiGatewayToken?: string;
  /** The underlying AI provider routed by the gateway (e.g. 'anthropic', 'openai') */
  aiProvider?: string;
}

export function generateMuPluginContent(config: MuPluginConfig): string {
  const {
    webhookUrl,
    webhookAuthToken,
    siteId,
    aiGatewayUrl,
    aiGatewayToken,
    aiProvider,
  } = config;

  // Determine AI Gateway port from URL if available
  const gatewayPort = aiGatewayUrl
    ? new URL(aiGatewayUrl).port || '13000'
    : '13000';

  return `<?php
/**
 * Nexus AI Connector Configuration
 *
 * Auto-generated by Local addon - provides:
 * 1. Webhook configuration for event tracking
 * 2. AI Gateway configuration for centralized AI routing
 * 3. Automatic caller detection for AI request tracking
 */

// ============================================================================
// Event Webhook Configuration
// ============================================================================

if (!defined('NEXUS_AI_WEBHOOK_URL')) {
    define('NEXUS_AI_WEBHOOK_URL', '${webhookUrl}');
}
if (!defined('NEXUS_AI_AUTH_TOKEN')) {
    define('NEXUS_AI_AUTH_TOKEN', '${webhookAuthToken}');
}
if (!defined('NEXUS_AI_SITE_ID')) {
    define('NEXUS_AI_SITE_ID', '${siteId}');
}

// Enable WordPress debugging for Nexus AI event logging
if (!defined('WP_DEBUG')) {
    define('WP_DEBUG', true);
}
if (!defined('WP_DEBUG_LOG')) {
    define('WP_DEBUG_LOG', true);
}
if (!defined('WP_DEBUG_DISPLAY')) {
    define('WP_DEBUG_DISPLAY', false);
}

${aiGatewayUrl && aiGatewayToken ? `
// ============================================================================
// AI Gateway Configuration (Ollama proxy — for local model support)
// ============================================================================

if (!defined('NEXUS_AI_GATEWAY_URL')) {
    define('NEXUS_AI_GATEWAY_URL', '${aiGatewayUrl}');
}
if (!defined('NEXUS_AI_GATEWAY_TOKEN')) {
    define('NEXUS_AI_GATEWAY_TOKEN', '${aiGatewayToken}');
}
if (!defined('NEXUS_AI_GATEWAY_PORT')) {
    define('NEXUS_AI_GATEWAY_PORT', '${gatewayPort}');
}
` : ''}
// The underlying provider the gateway is currently routing to.
// Used by ai-provider-for-local-gateway to expose the right model list.
if (!defined('NEXUS_AI_PROVIDER')) {
    define('NEXUS_AI_PROVIDER', '${aiProvider ?? 'anthropic'}');
}

// ============================================================================
// AI CALLER DETECTION: Track which plugin/feature makes AI requests
// ============================================================================

/**
 * Detect which WordPress plugin, theme, or core feature is making an AI call.
 *
 * Priority:
 * 1. Manual override (if developer provided caller info)
 * 2. Backtrace detection (plugin/theme from file path)
 * 3. Context detection (WordPress core features)
 *
 * @param array|null $existing_caller Manual caller override
 * @return array Caller information
 */
function nexus_ai_detect_caller($existing_caller = null) {
    // If caller already provided, respect it (but merge with detected source)
    $caller = is_array($existing_caller) ? $existing_caller : [];

    // Skip detection if plugin/theme already specified
    if (!empty($caller['plugin']) || !empty($caller['theme'])) {
        return $caller;
    }

    // Try backtrace detection
    $trace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 15);

    foreach ($trace as $frame) {
        if (!isset($frame['file'])) {
            continue;
        }

        // Plugin detection
        if (preg_match('#/wp-content/plugins/([^/]+)/#', $frame['file'], $matches)) {
            $caller['plugin'] = $matches[1];
            $caller['source'] = 'plugin';
            return $caller;
        }

        // Theme detection
        if (preg_match('#/wp-content/themes/([^/]+)/#', $frame['file'], $matches)) {
            $caller['theme'] = $matches[1];
            $caller['source'] = 'theme';
            return $caller;
        }
    }

    // No plugin/theme found - must be WordPress core
    $caller['source'] = 'core';

    // Try to detect which core feature
    if (empty($caller['feature'])) {
        $feature = nexus_ai_detect_core_feature();
        if ($feature) {
            $caller['feature'] = $feature;
        }
    }

    return $caller;
}

/**
 * Detect specific WordPress core feature from context.
 *
 * Uses request context (REST API, admin screens, etc.) to identify
 * which WordPress feature is making the AI call.
 *
 * @return string|null Feature identifier
 */
function nexus_ai_detect_core_feature() {
    // REST API requests (Block Editor)
    if (defined('REST_REQUEST') && REST_REQUEST) {
        $uri = isset($_SERVER['REQUEST_URI']) ? $_SERVER['REQUEST_URI'] : '';

        // Media uploads (likely alt text generation)
        if (strpos($uri, '/wp/v2/media') !== false) {
            return 'block-editor-alt-text';
        }

        // Post editing (likely title/excerpt generation)
        if (strpos($uri, '/wp/v2/posts') !== false) {
            return 'block-editor-posts';
        }

        // Page editing
        if (strpos($uri, '/wp/v2/pages') !== false) {
            return 'block-editor-pages';
        }

        // Generic block editor
        if (strpos($uri, '/wp/v2/') !== false) {
            return 'block-editor';
        }
    }

    // Admin screens
    if (is_admin()) {
        global $pagenow;

        if ($pagenow === 'post.php' || $pagenow === 'post-new.php') {
            return 'post-editor';
        }
        if ($pagenow === 'upload.php') {
            return 'media-library';
        }
        if ($pagenow === 'edit.php') {
            return 'posts-list';
        }
        if ($pagenow === 'edit-tags.php') {
            return 'taxonomy-editor';
        }
    }

    // WP-CLI
    if (defined('WP_CLI') && WP_CLI) {
        return 'wp-cli';
    }

    // Frontend (themes, shortcodes, widgets)
    if (!is_admin() && !wp_doing_ajax()) {
        return 'frontend';
    }

    // AJAX requests
    if (wp_doing_ajax()) {
        return 'ajax';
    }

    // Couldn't determine specific feature
    return null;
}

/**
 * Inject caller headers into AI Gateway requests.
 *
 * Uses http_request_args (not pre_http_request) because pre_http_request
 * is for preempting requests — modifying $parsed_args there has no effect.
 * http_request_args returns the modified args and actually affects the request.
 */
add_filter('http_request_args', function($args, $url) {
    // Only intercept requests to the AI Gateway routes.
    // These live on the webhook server under /ai-gateway/v1/ — NOT on the Ollama proxy.
    $webhook_url = defined('NEXUS_AI_WEBHOOK_URL') ? rtrim(NEXUS_AI_WEBHOOK_URL, '/') : null;

    if (!$webhook_url || strpos($url, $webhook_url . '/ai-gateway/') === false) {
        return $args;
    }

    // Initialize headers array if not set
    if (!isset($args['headers'])) {
        $args['headers'] = [];
    }

    // Don't override if caller headers are already present
    $has_caller_headers = isset($args['headers']['X-WP-Caller-Plugin']) ||
                          isset($args['headers']['X-WP-Caller-Theme']) ||
                          isset($args['headers']['X-WP-Caller-Feature']);

    if (!$has_caller_headers) {
        $caller = nexus_ai_detect_caller();

        if (!empty($caller['plugin'])) {
            $args['headers']['X-WP-Caller-Plugin'] = $caller['plugin'];
        }
        if (!empty($caller['theme'])) {
            $args['headers']['X-WP-Caller-Theme'] = $caller['theme'];
        }
        if (!empty($caller['feature'])) {
            $args['headers']['X-WP-Caller-Feature'] = $caller['feature'];
        }
        if (!empty($caller['source'])) {
            $args['headers']['X-WP-Caller-Source'] = $caller['source'];
        }

        $user_id = get_current_user_id();
        if ($user_id) {
            $args['headers']['X-WP-User-ID'] = (string) $user_id;
            $user = wp_get_current_user();
            if ($user && !empty($user->roles)) {
                $args['headers']['X-WP-User-Role'] = $user->roles[0];
            }
        }
    }

    return $args;
}, 10, 2);

// ============================================================================
// IMAGE GENERATION: Prepend local-gateway image models to the preferred list.
// Without this, the WP AI client looks for openai/google providers directly
// and finds none (since only local-gateway is registered).
// ============================================================================

add_filter('wpai_preferred_image_models', function($models) {
    $provider = defined('NEXUS_AI_PROVIDER') ? NEXUS_AI_PROVIDER : 'anthropic';
    $gateway_image_models = [];

    if ($provider === 'openai') {
        $gateway_image_models = [
            ['local-gateway', 'gpt-image-1'],
            ['local-gateway', 'gpt-image-1.5'],
            ['local-gateway', 'gpt-image-1-mini'],
            ['local-gateway', 'dall-e-3'],
            ['local-gateway', 'dall-e-2'],
        ];
    } elseif ($provider === 'google') {
        $gateway_image_models = [
            ['local-gateway', 'imagen-4.0-generate-001'],
            ['local-gateway', 'imagen-4.0-ultra-generate-001'],
            ['local-gateway', 'imagen-4.0-fast-generate-001'],
        ];
    }

    // Prepend gateway models so they are tried first
    return array_merge($gateway_image_models, (array) $models);
});
`;
}
