/**
 * AI Context File Generator
 *
 * Generates AI-CONTEXT.md files for WordPress sites to provide context
 * to AI coding assistants (GitHub Copilot, Cursor, Cline, Continue).
 *
 * The generated file includes:
 * - WordPress environment details
 * - Active plugins and theme
 * - AI Gateway configuration
 * - File structure and development guidelines
 */

import type { SiteMetadata } from '../metadata/SiteMetadataCache';

export interface AIContextData {
  siteName: string;
  siteUrl: string;
  sitePath: string;
  wpVersion?: string;
  phpVersion?: string;
  mysqlPort?: number;
  plugins?: Array<{
    name: string;
    title: string;
    version: string;
    status: 'active' | 'inactive';
  }>;
  theme?: {
    name: string;
    title: string;
    version: string;
  };
  aiGateway?: {
    url: string;
    token: string; // Will be masked
    models: string[];
  };
  generatedAt: number;
}

export class AIContextGenerator {
  /**
   * Generate AI context markdown for a site.
   *
   * @param data - Site data including metadata, AI config, etc.
   * @returns Markdown string ready to write to file
   */
  generateContext(data: AIContextData): string {
    const sections: string[] = [];

    // Header
    sections.push(this.generateHeader(data));

    // WordPress Environment
    sections.push(this.generateEnvironmentSection(data));

    // Active Plugins
    if (data.plugins && data.plugins.length > 0) {
      sections.push(this.generatePluginsSection(data.plugins));
    }

    // Active Theme
    if (data.theme) {
      sections.push(this.generateThemeSection(data.theme));
    }

    // AI Configuration
    if (data.aiGateway) {
      sections.push(this.generateAIConfigSection(data.aiGateway));
    }

    // File Structure
    sections.push(this.generateFileStructureSection());

    // Development Guidelines
    sections.push(this.generateGuidelinesSection(data));

    // Common Commands
    sections.push(this.generateCommandsSection());

    // Architecture Notes
    sections.push(this.generateArchitectureSection(data));

    // Debugging
    sections.push(this.generateDebuggingSection(data));

    // Footer
    sections.push(this.generateFooter());

    return sections.join('\n\n');
  }

  private generateHeader(data: AIContextData): string {
    const date = new Date(data.generatedAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    return `# AI Development Context - ${data.siteName}

Generated by Local AI Nexus on ${date}`;
  }

  private generateEnvironmentSection(data: AIContextData): string {
    const lines = ['## WordPress Environment', ''];

    if (data.wpVersion) {
      lines.push(`- **WordPress Version:** ${data.wpVersion}`);
    }
    if (data.phpVersion) {
      lines.push(`- **PHP Version:** ${data.phpVersion}`);
    }
    if (data.mysqlPort) {
      lines.push(`- **MySQL:** localhost:${data.mysqlPort} (root/root)`);
    }
    lines.push(`- **Site URL:** ${data.siteUrl}`);
    lines.push(`- **Admin URL:** ${data.siteUrl}/wp-admin`);

    return lines.join('\n');
  }

  private generatePluginsSection(plugins: AIContextData['plugins']): string {
    const lines = ['## Active Plugins', ''];

    if (!plugins || plugins.length === 0) {
      lines.push('*No plugins installed*');
      return lines.join('\n');
    }

    // Filter to only active plugins and sort by name
    const activePlugins = plugins
      .filter((p) => p.status === 'active')
      .sort((a, b) => a.title.localeCompare(b.title));

    if (activePlugins.length === 0) {
      lines.push('*No active plugins*');
    } else {
      for (const plugin of activePlugins) {
        const version = plugin.version ? ` (v${plugin.version})` : '';
        lines.push(`- **${plugin.title}**${version}`);
      }
    }

    return lines.join('\n');
  }

  private generateThemeSection(theme: AIContextData['theme']): string {
    if (!theme) {
      return '## Active Theme\n\n*Theme information not available*';
    }

    const version = theme.version ? ` (v${theme.version})` : '';
    return `## Active Theme

- **${theme.title}**${version}`;
  }

  private generateAIConfigSection(aiGateway: AIContextData['aiGateway']): string {
    if (!aiGateway) {
      return '## AI Configuration\n\n*AI Gateway not configured*';
    }

    const lines = ['## AI Configuration', ''];

    lines.push(`- **Gateway:** ${aiGateway.url}`);
    lines.push(`- **Gateway Token:** ${this.maskToken(aiGateway.token)}`);
    lines.push(`- **Provider:** Local Gateway (centralized credential management)`);

    if (aiGateway.models.length > 0) {
      lines.push(`- **Available Models:** ${aiGateway.models.join(', ')}`);
    }

    lines.push(`- **MU Plugin:** /wp-content/mu-plugins/nexus-ai-gateway-config.php`);
    lines.push('');
    lines.push(
      'All AI requests from this site route through the Local AI Gateway for tracking,',
    );
    lines.push(
      'rate limiting, and centralized credential management. Usage is tracked in the',
    );
    lines.push('Nexus Overview dashboard.');

    return lines.join('\n');
  }

  private generateFileStructureSection(): string {
    return `## File Structure

\`\`\`
/app/public/
├── wp-admin/           WordPress admin
├── wp-content/
│   ├── plugins/        Installed plugins
│   ├── themes/         Installed themes
│   ├── mu-plugins/     Must-use plugins (auto-load)
│   └── uploads/        Media library
├── wp-includes/        WordPress core
└── wp-config.php       Site configuration
\`\`\``;
  }

  private generateGuidelinesSection(data: AIContextData): string {
    const hasAI = !!data.aiGateway;

    const lines = [
      '## Development Guidelines',
      '',
      '### WordPress Best Practices',
      '',
      '- ✅ **Use hooks (actions/filters)** — Don\'t modify core files directly',
      '- ✅ **WP-CLI for operations** — Use `wp plugin list`, `wp option get`, etc.',
      '- ✅ **MU plugins auto-load** — No activation needed, just write to mu-plugins/',
      '- ✅ **Debug mode enabled** — Check `/wp-content/debug.log` for errors',
    ];

    if (hasAI) {
      lines.push('');
      lines.push('### AI Integration');
      lines.push('');
      lines.push('- Use WordPress AI Client library for AI features: `wp_ai_generate_text()`');
      lines.push('- AI requests automatically route through Local Gateway');
      lines.push('- Don\'t store API keys in the database — gateway handles credentials');
      lines.push('- See `wp-includes/functions-ai.php` for available AI functions');
    }

    return lines.join('\n');
  }

  private generateCommandsSection(): string {
    return `## Common Commands

\`\`\`bash
# Plugin management
wp plugin list
wp plugin activate <plugin-slug>
wp plugin deactivate <plugin-slug>

# Database operations
wp db query "SELECT * FROM wp_posts WHERE post_type = 'page'"
wp option get siteurl

# Evaluation (run PHP code)
wp eval "echo get_option('blogname');"

# User management
wp user list
wp user create testuser test@example.com --role=editor
\`\`\``;
  }

  private generateArchitectureSection(data: AIContextData): string {
    const hasAI = !!data.aiGateway;

    const lines = [
      '## Architecture Notes',
      '',
      '- **No server restarts needed** — PHP changes reflect on page refresh',
    ];

    // Check if ACF is installed
    const hasACF = data.plugins?.some((p) =>
      p.name.toLowerCase().includes('advanced-custom-fields'),
    );
    if (hasACF) {
      lines.push('- **ACF Pro available** — Use for custom fields on posts/pages/CPTs');
    }

    if (hasAI) {
      lines.push('- **AI Gateway tracking** — All AI usage visible in Nexus Overview dashboard');
    }

    lines.push('- **Auto-start/stop** — Halted sites auto-start for operations, then auto-stop');

    return lines.join('\n');
  }

  private generateDebuggingSection(data: AIContextData): string {
    const mysqlPort = data.mysqlPort || 3306;

    return `## Debugging

- **PHP errors:** \`/wp-content/debug.log\` (if \`WP_DEBUG_LOG\` enabled)
- **Database:** Access via Adminer or SequelPro (localhost:${mysqlPort}, root/root)
- **WP-CLI:** Run commands from Terminal (site must be running)
- **Local logs:** View in Local app → Site → Logs tab`;
  }

  private generateFooter(): string {
    return `---

*This file is auto-generated by Local AI Nexus. Edit with caution — changes may be overwritten.*`;
  }

  /**
   * Mask an auth token for display.
   * Shows first 8 characters, masks the rest.
   *
   * @param token - Full token string
   * @returns Masked token (e.g., "10177933-****-****-****-********70e20")
   */
  private maskToken(token: string): string {
    if (token.length <= 8) {
      return token;
    }

    // UUID format: 8-4-4-4-12
    // Show first 8, mask middle sections, show last 4
    const parts = token.split('-');
    if (parts.length === 5 && parts[4].length === 12) {
      // First section (8 chars) + mask middle + last 4 of final section
      return `${parts[0]}-****-****-****-${'*'.repeat(8)}${parts[4].substring(8)}`;
    }

    // Generic masking if not UUID
    if (token.length < 12) {
      // Too short for full masking, just show first 8
      return `${token.substring(0, 8)}${'*'.repeat(token.length - 8)}`;
    }

    return `${token.substring(0, 8)}${'*'.repeat(Math.min(token.length - 12, 32))}${token.substring(token.length - 4)}`;
  }
}
